### ISSUE TITLE
Planning video

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1012]
@matkoniecz staging super slow to load on new Mac causing problems with making video any thoughts?
can we go ahead and release onto main site once issues under deployment sorted?

**Comment by matkoniecz** [comment]
Can you share the video of slow loading?

From what I remember main site has more powerful server so it also would help

**Comment by polly64** [comment]
can't get file small enough to upload will share on one drive

**Comment by matkoniecz** [comment]
OK, so it seems that extreme slowness is limited.

It is unclear what is going on

- that specific mac device has also other problems
- there are other slowdowns but for example also leaflet-based openstreetmap.org loads fine
- colouring London is affected, inclduing historical map display
- in Firefox browser console has some network-related warnings, but nothing clearly about CL

The plan is to exchange the laptop for now.

Potential next steps

- test is Chrome also affected
- get full browser console from Safari, Firefox and Chrome
- is for example https://maps.nls.uk/geo/roy/#zoom=11&lat=57.3290&lon=-4.4290&layers=0 also affected
- debug it remotely
