### ISSUE TITLE
Disable historic overlay on category change

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#1037]

**Comment by mdsimpson42** [comment]
I take it we don't want to simply 'reset layers' when the category changes, as there may be layers that you want to stay active between categories?

Is there a piece of code that is called when the category changes? I'm looking through the logic but struggling to find a good place to add code that would turn off the historic overlay when you click on another category...

**Comment by mdsimpson42** [comment]
Duplicate of #1037

**Comment by mdsimpson42** [comment]
Duplicate of #1141
