### ISSUE TITLE
assign more memory to the staging server (?)

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#1040]
right now reloading staging server very often fails with out-of-memory issues and it is necessary to reboot it

maybe assigning more memory would be a good idea

**Comment by mdsimpson42** [comment]
We have currently reduced Staging back to size: Standard_B2ms. I think Production is currently the same size too, as we were trying to save money while the subscription was sorted out. 

We may need to revisit this, see what we can afford, what the minimum specs are and what machine size we should switch to for Staging and Production, but there's an open issue for that - #1069  - so I'm closing this for now.
