### ISSUE TITLE
Edit planning key for Status

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1043]
@matkoniecz not urgent but I think ideal if we could only see  the 3 options for planning application status options on key (i.e. all, 12 months, last 30 days) when the 'Planning Application Information' & 'Past application' information sections - at the moment you get designation etc as well.

So to get to the designation info your only route would be to go to the protection section and click pink button or to chose as a layer (we'd need to add this). I think this might work better what do you think? 

Can you also hide empty map as public will immediately ask what this is? Can't remember why we have this?

**Comment by matkoniecz** [comment]
> Can you also hide empty map as public will immediately ask what this is? Can't remember why we have this?

#1051 (the idea was to provide way of looking at overlay data without distraction of underlying data)

**Comment by matkoniecz** [comment]
> ideal if we could only see the 3 options for planning application status options on key (i.e. all, 12 months, last 30 days) when the 'Planning Application Information' & 'Past application' information sections - at the moment you get designation etc as well.

Right now I see no obvious reliable solutions here. Maybe tracking which sections are collapsed/open would work.

**Comment by polly64** [comment]
think fine at moment let's talk more re improvements maybe we can add to future stuff
