### ISSUE TITLE
How do we direct people to planning feedback before unactivated items are activated?

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1048]
@matkoniecz @mdsimpson42 shall we make a new section in the discussion forum at put at the top called ' Planning section comments' .
Then under the crowdsourced planning application bit which isn't activated write at bottom ' Until this section is activated please report inaccuracies or problems on the Discussion Forum' and highlight discussion forum as link

I'm concerned there's nowhere for people to tell us there are errors and it will get discussion forum more visible

**Comment by mdsimpson42** [comment]
Yes, I think so. We could add a new category on the Discussions section, so people can have discussions/make suggestions and we keep them all in the same place. Then link to it from the relevant section on the CC menu.

**Comment by polly64** [comment]
@mdsimpson42 could you add this today?

**Comment by mdsimpson42** [comment]
I've added the extra text to the yellow label in this section:  

![image](https://user-images.githubusercontent.com/21125422/212884577-38cb6f29-31e4-40ab-8b9f-e08c66a5f5fe.png)

Which links to a new category in Discussions [here](https://github.com/colouring-cities/colouring-london/discussions/categories/planning-section-comments)

**Comment by matkoniecz** [comment]
@polly64 

> discussion forum

Have you meant Github discussion forum of Discourse discussion forum at https://discuss.colouring.london/categories ?

**Comment by polly64** [comment]
@matkoniecz lets leave GitHub forum for moment and focus on Colouring London discussion- we can always shift it if necessary
