### ISSUE TITLE
Changes to Categories (from meeting 02/02)

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1074]
Changes to the categories to make it more international-friendly, including typo fixes and changes to category wording.

**Comment by mdsimpson42** [comment]
@polly64 once Mateusz has deployed the changes, we'll let you know. I'll leave this issue open, so if there are any mistakes or additional related changes, then we can keep track of them here?

**Comment by polly64** [comment]
@mdsimpson42 thanks Mike

**Comment by matkoniecz** [comment]
@polly64 Changed deployed to the production server
