### ISSUE TITLE
Only buildings rate grade E or higher maybe rented -> Only buildings rate grade E or higher may be rented (?)

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#1078]
> Display Energy Certificate (DEC) Any public building should have (and display) a DEC. Showing how the energy use for that building compares to other buildings with same use

is "maybe" supposed to be "may be"?

Tooltip for "Non-domestic Building Energy Rating" in Energy Performance

@polly64

**Comment by matkoniecz** [comment]
ops, that was just recently fixed

**Comment by matkoniecz** [comment]
https://github.com/colouring-cities/colouring-london/blob/6dd356bbeb71e7f6e69d7baafe87e8712735f122/app/src/frontend/config/data-fields-config.ts#L439

**Comment by matkoniecz** [comment]
![screen](https://user-images.githubusercontent.com/899988/219308658-d6d54d1a-a8b8-4de2-941a-96831df8fb53.png)

**Comment by polly64** [comment]
@matkoniecz yes should be 'may be'
