### ISSUE TITLE
Repository description should be changed

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#1080]
It still has

>  Collecting data on London's buildings 

See say https://github.com/colouring-cities

**Comment by matkoniecz** [comment]
I see that it is changed

**Comment by polly64** [comment]
@matkoniecz thanks, bit of a flurry of emails re the server credits- if u have a moment could you possibly just look at the last email and see what u think re amount we should apply for? and any other thoughts
