### ISSUE TITLE
Make future Planning button red

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1085]
@matkoniecz  could we make the clickable map button red like other?

<img width="461" alt="Screenshot 2023-02-14 at 13 28 04" src="https://user-images.githubusercontent.com/42236514/218752867-ba0ca223-1c3a-445e-8dfa-7eb9afc0bdce.png">

**Comment by polly64** [comment]
thanks

**Comment by matkoniecz** [comment]
@polly64 

Also the button in "Heritage assets and building protection" section, right?

**Comment by polly64** [comment]
@matkoniecz yes any buttons that should bring up maps
