### ISSUE TITLE
Adding Colouring Australia walkability index to core 'Street Context' code

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1086]
Hi @mdsimpson42 could we add the open walkability index from the Colouring Australia platform at end of 'Street context'. Could you generate the visuals for this using the code? Would be great to show cross fertilisation of ideas at AIUK

**Comment by mdsimpson42** [comment]
I can't see the walkability index on the Colouring Syndney site, I don't have a log in to edit. But looking at the code on the Colouring Australia repo: https://github.com/colouring-cities/colouring-australia/commit/f8f30759957ee259d4a562128d766c4fbe041e04

It looks like its a rating of between 0 - 100 (percent?). 

- [ ] I can add a numerical field where the numbers between 0 and 100 are valid.
- [ ] Are there instructions for how to work out/find out the walkability index of a building?

**Comment by polly64** [comment]
think you need to talk to Matt Ng at UNSW about this - I thought colouring Australia and Bogota repos weren't visible or did I get that wrong

**Comment by mdsimpson42** [comment]
There is a [colouring-australia](https://github.com/colouring-cities/colouring-australia) repo, but it hasn't been updated in a while (the walkability index was the last thing added to it). Presumably, there are separate repositories for each city somewhere, but not on the [colouring-cities](https://github.com/colouring-cities) organisation.

**Comment by mdsimpson42** [comment]
Just checking whether this is something we want to add into the Core platform or whether we just want to add it in Colouring Britain for now?
