### ISSUE TITLE
Move content from pages.colouring.london

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1088]
Remove various links to the external site (pages.colouring.london) and recreate those pages within the app itself.

"About, Data Categories, Who's Involved..." etc from this section of the menu:

![image](https://user-images.githubusercontent.com/21125422/219008016-07b85246-4200-494b-bc32-fe7669014fdc.png)

**Comment by mdsimpson42** [comment]
What about "Discussion Forum" and "Blog", which link to https://discuss.colouring.london/? 
We can link to GitHub Discussions instead, but we won't easily be able to copy across Discussion history?

**Comment by mdsimpson42** [comment]
Every page in the menu now links to either GitHub or onto pages within the platform, apart from the "Who's involved?" page. Could this be added to [https://github.com/colouring-cities/colouring-cities.github.io](https://github.com/colouring-cities/colouring-cities.github.io) (so it appears on [ColouringCities.org](ColouringCities.org))?

- [ ] Move the "Who's involved?" page to... somewhere. (Then this issue can be closed)

**Comment by polly64** [comment]
@mdsimpson42 Can we create link  option in code to partners' Open manual Country pages. For Colouring London link to https://github.com/colouring-cities/manual/wiki/M3.-COLOURING-BRITAIN

**Comment by mdsimpson42** [comment]
> @mdsimpson42 Can we create link option in code to partners' Open manual Country pages. For Colouring London link to https://github.com/colouring-cities/manual/wiki/M3.-COLOURING-BRITAIN

Yes. We could add an "About Colouring [City Name]" to the menu (under where it currently says "About the Colouring Cities Research Programme"), and put the link in the Config file. I'll do that for now, and we can always change how it works later on?

- [ ] Add "About Colouring [City Name]" to the menu
