### ISSUE TITLE
Documentation for using Colouring Core

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1106]
I think it would be useful to create documentation for users on how to stay in sync with the Colouring Core platform. Perhaps adding a new .md file here: https://github.com/colouring-cities/colouring-core/tree/master/docs.

This should include:
- Forking the project into another organisation
- How to copy the code from colouring-core into a new repository on the CCRP organisation
- How to pull updates from colouring-core into your repository
- How to push changes from your repository back to colouring-core

**Comment by mdsimpson42** [comment]
Turns out you can fork into the same repository, as long as you rename the new repository (I created colouring-newcastle as a teas this morning and it seemed to work - Google lied to me!). 

So, I'll update the instructions on how to update using the forks in the repository. But I guess the git command line commands may still be useful to people working on servers and/or people who don't used GitHub Desktop?

**Comment by matkoniecz** [comment]
> you said you'd worked out how to 'fork' the repository within the organisation from the command line?

I think that it is about https://github.com/colouring-cities/archive-colouring-core-first-attempt/pull/5#issuecomment-1415809415

```
git checkout fork
git commit -m "my changes"
git merge my_local_branch
git checkout master
git fetch upstream
git reset --hard upstream/master
git checkout fork
git merge master
```

this will commit some local changes, merge local brach and merge in new commits from upstream

**Comment by mdsimpson42** [comment]
First pass of the documentation is complete. New issues will be created to add to it/fix it.
