### ISSUE TITLE
Change Welcome text

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1116]
Hi @mdsimpson42 could you change the intro text have made a few edits and also enable partners to add their own Colouring Cities above  e.g. **_Welcome to Colouring Dresden/Athens_** etc rather than _Welcome to Colouring Cities_ 

Colouring Cities platforms provide over 100 types of open data relating to the composition, performance and dynamic behaviour of building stocks. 

The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute, involves an [international consortium of academic institutions](https://github.com/colouring-cities/colouring-cities.github.io) involved in building research. Our aim is to maximise accessibility to building-level data across countries, to help improve stock quality, efficiency, sustainability and resilience and meet net-zero goals.

New data and features are added all the time. We are keen to engage as many people as possible in platform development. Whether you are a resident, or a stakeholder in academia, government, industry or the third sector, any help you can give colouring in our _**Colouring x map (e.g.Dresden/London/Britain/Bahrain)**,_ and enriching and verifying our open databases with your knowledge, is greatly appreciated.

All our [data](https://colouringlondon.org/data-extracts.html) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information on the CCRP for anyone interested in our research.

**Comment by mdsimpson42** [comment]
The first part is already done. It will say "Welcome to Colouring [City Name]", once the city name has been set in the config file. (It says "Welcome to Colouring London" on Staging, but Production won't update - see issue #1129)

I've also added a "custom blurb" that is displayed at the start of the paragraph. So, London's is "Colouring London is the prototype for the Colouring Cities Programme", but they can replace that opening sentence with a piece of custom text. (The default is: "Colouring [City Name] is part of the Colouring Cities Programme".)

I suggest leaving this for now, at least until we can get the version on Production up to date, then we can change it once the correct text is actually being displayed!

-----

I will make the other changes on Colouring Core and get them deployed to Staging ASAP.

**Comment by polly64** [comment]
@mdsimpson42 have made some corrections in bold

Welcome to Colouring London!

Colouring London is a free knowledge exchange platform designed to provide over ****120 types of open data on buildings to help make the cities more sustainable.**

Colouring London is also the prototype for the Colouring Cities Research Programme (CCRP)  **The CCRP is** led by the Alan Turing Institute, and **brings together [an international network of academic institutions](https://github.com/colouring-cities/colouring-cities.github.io) involved in building research. Our aim is to maximise accessibility to building-level data across countries, to help improve stock quality, efficiency, sustainability and resilience and meet net-zero goals.

New data and features are added all the time. We are keen to engage as many people as possible in platform development. Whether you are a resident, or a stakeholder in academia, government, industry or the third sector, any help you can give colouring in our Colouring Cities maps, and enriching and verifying our **open database** with your knowledge, is greatly appreciated.

All our [data](https://colouringlondon.org/data-extracts.html) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under our open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information on the CCRP for anyone interested in our research.
