### ISSUE TITLE
tweaks to land use key

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1117]
@mdsimpson42 could you change default to 'land use' , not 'domestic/non-domestic' on key- and also change key titles to reda' domestic? not 'is domestic?
<img width="1451" alt="Screenshot 2023-03-08 at 18 12 13" src="https://user-images.githubusercontent.com/42236514/223795810-7cb37112-9612-4ff9-a738-58d90644c72e.png">

**Comment by mdsimpson42** [comment]
To clarify:
1. Change the dropdown menu on the key so that "Land Use" is the default category.
2. Change the wording of the other category on the key, currently "Is domestic building?" to just "Domestic?"

(Please confirm the wording for item 2 - it's not clear in the issue text)

**Comment by polly64** [comment]
@mdsimpson42 yes 'Land use default and should be 'Domestic building'
