### ISSUE TITLE
Add Building Survival Status 

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1127]
Add survival status to buildings. 

Four options/colours:
- Same as Historical Map (Unchanged)
- Similar to Historical Map (Some Changes)
- Historical Building Demolished
- Current Building on Previous Green Space

Plus source information

Also, a new filter on the key to visualise Survival Status on the map.

Automatically switch to Survival Status view when the Historical Map layer is activated?

**Comment by mdsimpson42** [comment]
@tomalrussell @matkoniecz 
How do I add an extra column to the building table? Obviously, I can add the table to my local database, but do I need to add it to any scripts, for example, to make sure that field is added to the databases on other machines?

**Comment by tomalrussell** [comment]
Take a look in https://github.com/colouring-cities/colouring-core/tree/master/migrations

**Comment by matkoniecz** [comment]
To be more specific see say https://github.com/colouring-cities/colouring-core/blob/master/migrations/031.landowner.up.sql (note .down mirroring it)

See also https://github.com/colouring-cities/colouring-london-config#migrations

**Comment by mdsimpson42** [comment]
The main task is done, there are some bugs and additional work to do, but they are already documented in separate issues.
