### ISSUE TITLE
Survival data not displaying correctly on Historical Maps

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1130]
![survival 1b](https://user-images.githubusercontent.com/42236514/230444350-94ea70a8-2687-4221-a207-b932a01116d3.JPG)
![survival 1a](https://user-images.githubusercontent.com/42236514/230444361-a2c2df15-762d-41e6-9e8c-2ae4cfc5d586.JPG)

_Originally posted by @polly64 in https://github.com/colouring-cities/colouring-core/issues/1129#issuecomment-1499350448_

**Comment by mdsimpson42** [comment]
Some building data is not being shown when switching to Historical Maps. Mateusz suggested it may have something to do with layer priority.

https://github.com/colouring-cities/colouring-core/issues/1129#issuecomment-1499352511
https://github.com/colouring-cities/colouring-core/issues/1129#issuecomment-1499354897

**Comment by mdsimpson42** [comment]
I cannot replicate this. I've tried it in Edge, Chrome and Firefox on my PC and laptop, but all the buildings seem to display correctly. 

Could this be a Mac issue? Or are the tiles just updating slowly?

**Comment by polly64** [comment]
@mdsimpson42 let's look on a shared screen at this. Imagining we are still only able to look at on staging?
<img width="1215" alt="Screenshot 2023-04-13 at 09 12 03" src="https://user-images.githubusercontent.com/42236514/231698453-8f1587a2-a91f-4f5f-b0c5-078477a7b93e.png">
<img width="1199" alt="Screenshot 2023-04-13 at 09 10 47" src="https://user-images.githubusercontent.com/42236514/231698484-de681f3a-77c0-4e5a-a0b6-2bd2f2496d36.png">

≈

**Comment by mdsimpson42** [comment]
After some testing, I've discovered that:

- If you edit the historical status on the 'normal' map, without the 1890s map overlayed, then it immediately updates correctly. 
- If you do it while the historical map is overlayed, then it doesn't update automatically, but it eventually does if you zoom out or toggle the historical map on and off a couple of times.

(This could be partly because it takes a while for the tiles to refresh?)

**Comment by mdsimpson42** [comment]
> @mdsimpson42 (to look at in May) copy and paste buttons copying age not survival. Also can we add verification button under status

I'll create a separate issue for the "copy" bug - as this might apply to multiple categories (but that's a separate problem). 

Closing this issue now it has been resolved by Mateusz.
