### ISSUE TITLE
Issue Organisation

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1131]
Because of the restructure we (may) need to reorganise the issues. All of the issues that were on the Colouring London repository are now on the Colouring Core repository, so any issues that are specific to Colouring London and not the core platform should be transferred across.

This may also be a good time to close any issues that are resolved or are no longer relevant.

**Comment by polly64** [comment]
@mdsimpson42 sure shall we look at today?

**Comment by mdsimpson42** [comment]
There may be some issues that are specific to Colouring London that should not be on the Core Platform. The issues have not been copied across already, so do not close these issues, but "Transfer" them to Colouring London instead. 

This can be done by clicking Transfer on the menu to the right-hand side of the issue:
![image](https://user-images.githubusercontent.com/21125422/232054388-f5025565-dbb2-4fa6-acd4-9d560a28ee44.png)

**Comment by polly64** [comment]
@mdsimpson42 ok thanks

**Comment by mdsimpson42** [comment]
Reopened - We haven't done this yet! Ideally, we need to go through and close any issue as either "finished" or "not planned" to cull the number of open images, or transfer them to the relevant repository, or add them to the relevant project and prioritise them.
