### ISSUE TITLE
Priority- risk management test feature for 'Resilience section'

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1136]
Hi @mdsimpson42  could you spend a half day on Monday adding the following Disaster management feature to the Resilience section  (@matkoniecz copying you in as you may be interested in this section and would be good to discuss with you later). (See also https://github.com/colouring-cities/colouring-core/issues/627 which includes image of London 1940s bomb damage map from which design brief derived, initially as an immediate response to Beirut Blast).

Could you:
i)  Using the same font  and format as for Survival', create a new title at the top of the 'Resilience' section' called 'Disaster management' . Below this create a second title called 'Resilience indicators'  and place all existing subsets within this second section

ii)  **In the new 'Disaster management'** section could you

a) Copy and paste the blue box from the  'Survival/Age and History' section and change text to read: 'This feature is designed to help communities capture data on the state of buildings during major disasters to support emergency services. and to record damage to aid reconstruction programmes.'

b)  Copy and paste the map link button (from the 'Survival'/'Age and History' section) and change the text to read  **'Click here to show disaster management maps'** 

c) Add Question 1:  **'What type of disaster management do you wish to collect data for?**. Then copy and paste the dropdown menu from the _'Community'_ section to allow for combined options (use the code relating to why users like a typologies and think they contribute to the city).  Change the text to offer the following options or combinations of these: **Flood, Earthquake, Hurricane, Fire, Extreme heat, political/war damage, Other human blast damage/spills etc, Other**

d) Add Question 2: 'How severe do you assess the damage to be? Then copy and paste the dropdown menu from the _Age & History/Survival_ section and change options to: **Building destroyed, Very severe, Severe, Moderate, Minimal and No damage able to be seen**. Then Copy and paste the 'Verification button'

e) Hide the current key as it is not needed and create a new key and title this as **'Severity of damage'** (NB there is no issue of having to resolve the map button automatically changing the key before the Beirut WiDs event ). In the longer run we need to be able to bring up and archive maps from different dates for different disasters but this is a bigger job

f) Add Question 3: 'Please add a method of assessment'. Then Copy and paste the dropdown menu again from the survival section and change text to the following options: **'Citizen/Passerby by eye, Government assessor, Specialist emergency group/charity. Other** . Then copy and paste the 'Verification button'

g) Add Question 4 ' Please add a source link to official documentation where applicable'.  Copy and paste source feature from survival. Allow for multiple source links.

(note for PH to discuss with SARAID, GEM, Cambridge Earthquake Impact Database +)

**Comment by mdsimpson42** [comment]
I'm part way there; I've put the existing data fields into a new concertina called "Resilience" and added a "Disaster Management" one at the top. I've added most of the fields and the button. Just the source and key to go. 

Does this look roughly like you expected?

![image](https://user-images.githubusercontent.com/21125422/232541711-68acd3d0-9733-42f3-9b97-4e42283d0a51.png)

Are there any existing categories that allow for multiple Sources? I had a quick look but I couldn't see any, only the section in Land Use that lets you add multiple Current Land Use entries...

**Comment by polly64** [comment]
@mdsimpson42 looks great- yes I think if you start adding data to the Lifespan section  think it will open up options to add sources.

**Comment by polly64** [comment]
@mdsimpson42 actually have just looked at and it's not a source but a whole entry . but in Team you can find the code
<img width="477" alt="Screenshot 2023-04-17 at 17 21 10" src="https://user-images.githubusercontent.com/42236514/232549053-0c0086d3-0a89-43d2-823b-72db792b9040.png">

**Comment by polly64** [comment]
also can you call the second section (with the existing unactivated categories) 'Resilience indicators'

**Comment by polly64** [comment]
lAso adding link to Open Lebanon mapping by Melda Salhab and colleagues who we were were discussing use of Colouring Beirut for emergency mapping with at time of blast,  Open lebanon used footprints  in their 'Beirut recovery map' to capture severity of damage as can be seen here https://www.beirutrecovery.org/

@MeldaS hi! if you could add any links to any reports or papers that came out of this that would be great
