### ISSUE TITLE
Testing Colouring Core

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1137]
We could do with a way of testing new features developed on the Core platform without having to merge those features into the main branch and then syncing the changes to Colouring London. (For example, the changes currently on the [feature/disaster-management](https://github.com/colouring-cities/colouring-core/tree/feature/disaster-management) branch.

My thoughts:
- This would only be on Staging.
- We can check out the Core repo into a folder called 'colouring-core' (alongside the 'colouring-london' folder)
- Then if we run the build, pre-deploy and deploy scripts, but use the core folder instead of the London folder, it should deploy the core app instead of the London app.

Does that make sense? I guess the best thing to do would be to create a "core-scripts" folder with the modified scripts in them and run them from there instead? We're already backing up the previous version of the app, so it shouldn't cause any problems?

I'm open to any thoughts or suggestions. Unless there are any objections or changes, I would like to do this ASAP, so that Polly can test these new features before I merge them...

**Comment by mdsimpson42** [comment]
I will set it up today so that you can deploy colouring-core on stating instead of colouring-london, just for testing purposes. 

Maybe in the long run, we can set it up so that:
- colouring-london is at: https://cl-staging.uksouth.cloudapp.azure.com/colouring-london
- colouring-core is at: https://cl-staging.uksouth.cloudapp.azure.com/colouring-london

Do we think that might be possible (without too much additional work)?

**Comment by matkoniecz** [comment]
> Do we think that might be possible (without too much additional work)?

And without paying for one more server...

One thing that is not really being tested here is database structure what worries me a bit. Though rebuilding test database on such switch between London/Britain and Core would be likely tricky, and potentially taking long time. 

But I already had cases where serious bug was present because I tested things on staging where database structure was different than on production (due to testing some migrations already).

**Comment by polly64** [comment]
Of course let's all talk about this when Mike and I are back week after next as obviously v important issues raised

**Comment by mdsimpson42** [comment]
We have a way of testing this on Staging for now. It uses the same database for both platforms, but it at least enables us to test them both somewhere for now
