### ISSUE TITLE
Survival Data not updating automatically on Historical Maps

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1143]
When you change the suvival status of a building and click 'save', it doesn't automatically update when viewing the historical maps.

Note: 

- It works correctly when viewing the 'regular' map.
- The colours on the historical map do update when you zoom in/out.

**Comment by mdsimpson42** [comment]
@tomalrussell Any idea why the map isn't updating automatically when the survival status is changed?

**Comment by polly64** [comment]
@mdsimpson42 could you update?
Also can we have option to either layer map in front of polygons too, thanks

**Comment by polly64** [comment]
@matkoniecz would there be any chance if you trying to resolve this one? (Will also be relevant to layering of Loughborough historical maps using open historical  os maps from the national library of Scotland)

**Comment by matkoniecz** [comment]
@polly64 I am still looking into it

**Comment by polly64** [comment]
thanks v much @matkoniecz
