### ISSUE TITLE
Colouring Cities.org SSL Certificate

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1150]
There are concerns about the "not secured" warning that comes up when you visit [colouringcities.org](https://colouringcities.org)/[colouring-cities.github.io/](https://colouring-cities.github.io/)

This is because it is trying to use a secure connection (https), but it doesn't have a valid SSL certificate.

It looks like it is possible to set this up, as per this article: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by tomalrussell** [comment]
Hi @mdsimpson42 - I just saw this issue in a notification, it's a checkbox to change as described in the docs you link, so I just ticked it, should be fine now.
