### ISSUE TITLE
Summary of minor tweaks to interface pre  updates to typology and construction sections

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1165]
**All categories** - 

- [x] #1174
- [x] Change drop down for' source type' to read
-  Assessed by eye
-  Assessed using expert knowledge of building or building type
-  Assessed using streetview photographs or satellite imagery
-  Assessed by specialist emergency group
-  Live streamed from a government source
-  Current government record/dataset 
-  Independently managed public database
- Commercial database
- Inferred computationally using existing open attribute data'
- [x] #1168

**Location**

- [x] Change hint to read 'non-residential' not 'well known public' and place full stop outside bracket
- [x] Change lower to upper case C on 'city'
- [x] Change Postcode to Area code/Postcode- so all platforms say 'Area code' 
- [x] #1176
- [x] OSM ID needs source type and source link

**Land use**

- [x] Change italic text to read 'The vast majority of properties are residential (93% in the UK) - make brackets changeable for countries
- [x] For main titles change first to 'Residential/Non- residential land use data (general)'

**Typology**
See issue to update wholes ection

**Size**
- [x] Move ' frontage width' to above plot size
- [x] Activate plot size categories
 except plot dimensions which should be removed 
- [x] For land parcel geometry link keep the source type and the link

**Construction**
See issue to update whole section

**Age and history**
- [x] #1169
- [x] ~~Remove the orange box saying this section is under development under~~ (part of above issue)
- [x] **_Constructions and demolitions (???)_**
- [x] check survival map works
- [x] link survival map to key

**Street Context**

- [x] Under gardens change title to 'Does the building have a garden? 
- [x] Under gardens, change so it reads 'Does the building have a front garden- 'is it mainly green/planted;  'Does the building have a back garden- 'is it mainly green/planted; is the building is a block of flats does it have  green around it Yes/no? 
- [x] Under gardens add source type/source
- [x] Under Street Width and Pavement width add (m)' and add separate sources for each
- [x] create https link for Street network geometry  and source type
- [x] Add (m) to distance to trees ad green space for both. Change to 'Approximate distance', and add sources for each
- [x] Activate these as they are pretty straightforward and don't have complex dropdowns 

**Team**

- [x] #1175
- [x] Change 'Dates of construction/extension' title to ' Does data relate to the main building or an extension?
- [x] **_Repeat question and add  dropdownto choose from (???)_**
- [x] Create new issue to link year of main construction/extension from data in Age history and remove ' year of construction'

**Planning Controls**
No comments

**Energy performance**
For Colouring London 

**Resilience**
- [x] Remove "show disaster maps" button.
- [x] change drop down for the standard one but add 'Specialist emergency body'

**Community**
- [x] Change italics to read 'Please Note: We are only currently collecting data on non-residential buildings
- [x] ~~Change~~ Add map button: "Click here to see 'liked' non-residential buildings"
- [x] Change dropdown for 'is the building in public/community ownership' to (Separate issue created - #1179)
- State owned
- Charity owned
- Community owned
- Owned by other non-profit
- Privately owned (non-corporate)
- Privately owned (corporate)
- Other

**Comment by polly64** [comment]
@mdsimpson42 I'd focus on all of these and then move on to typology and construction next week

**Comment by mdsimpson42** [comment]
Building footprint ID and UPRN appear to be automatically filled/derived from somewhere. If they can't be edited, do they need sources? There is a link to the relevant sites in the hint.

How do you generate a link that includes the ID/number? Can you like to specific buildings with the relevant datasets? 

For example, for OpenStreetMap ID, could we link to "openstreetmap.org/way/{OSM-ID-NUMBER}", then they could verify it. (e.g. Euston is correct: [https://www.openstreetmap.org/way/4960746](https://www.openstreetmap.org/way/4960746))

**Comment by mdsimpson42** [comment]
Similarly, is the Land parcel geometry (INSPIRE polygons) an open dataset that we can link to in the same way as OSM (see above)?

**Comment by mdsimpson42** [comment]
Survival maps work (pending #1142)

**Comment by mdsimpson42** [comment]
> Create new issue to link year of main construction/extension from data in Age history and remove ' year of construction'

The "year of construction" is already the same data field in both Age & History and Team categories.

**Comment by mdsimpson42** [comment]
> Add https so no free text boxes

There may be a problem changing existing fields: what do we do with the existing data?

**Comment by mdsimpson42** [comment]
> Change map button to say ' Click here to see 'liked' non-residential typologies mapped

Which map button? (Community)

**Comment by polly64** [comment]
@mdsimpson42 I'm sure tom activated the OSM links could you check something hasn't been turned off of check with @matkoniecz many thanks

**Comment by mdsimpson42** [comment]
> Add map button: "Click here to see 'liked' non-residential buildings"

Done (but "liked non-residential buildings" is enabled by default, so the button will be green by default, but will change as the key changes/other buttons on the page are pressed).

**Comment by mdsimpson42** [comment]
Separate issues were created for the remaining tasks. Committed to ui-refactor, pending testing on Staging.

**Comment by polly64** [comment]
[CCRP Datasetsfor rev3 22.6.2023.xlsx](https://github.com/colouring-cities/colouring-core/files/11837277/CCRP.Datasetsfor.rev3.22.6.2023.xlsx)
