### ISSUE TITLE
Survival map tweaks

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1181]
Hi @mdsimpson42 tweaks to the survival maps below

- [x] make red outlines get thinner as user zooms out so think they disappear at full zoom
- [x] make red outlines a bit thicker when you are zoomed in as they are hard to see- but not too thick that they obscure buildings underneath
- [x] create an option that allows you to bring historical map to front of polygons so that you can read it in its original form

**Comment by mdsimpson42** [comment]
Done. 

- The outlines are now blue. They are thicker when you zoom in, thinner when you zoom out and disappear above a certain zoom level.
- There are also now separate layers (with an option/button for each), one with the footprints on and one without
