### ISSUE TITLE
Age - Add Normal Source Type for Building Age Data

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1193]
I made a note to add a "normal" Source Type (and links), as well as a "specific historical source type" to the Age and History Category. I believe the suggestion was to rename the existing source type (but keep it) and add an additional field(s). 

The fields will have to be added to the interface, added to the code/data model and added to the database.

(Also, worth double-checking that I correctly understood my notes!)

**Comment by polly64** [comment]
@mdsimpson42 rename as ' Historical source type, and then add standard 'Source Type' below
