### ISSUE TITLE
Reorder Land Use options

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1194]
Connected to (#1149) 

Reorder the options that pop up to Autofill "Current land use(s)" (under "Specific Land Use" on the "Land Use" category), as follows:

Residential, Residential garden buildings, Hotels Boarding Houses and Guest Houses, Residential Institutions, Unclassified presumed residential, Shops, financial and professional services,  Manufacturing, Offices, Storage, Wholesale distribution,  Restaurants and cafes, Bars and Nightclubs, Medical/Health Services, Places of worship, Community services, Amusement and show places, Sports facilities and grounds, Other outdoor amenities/open spaces, Libraries Museums and galleries, Holiday Parks and Camps, Allotments and farms, Transport, tracks and ways, Transport- terminals and interchanges, Car Parks, Vehicle storage (private), Goods and fright terminals, Waterways, Post and telecommunications, Water Storage and treatment, Energy production and distribution, Refuse disposal, Defence, Cemeteries and Cremetoria, Agriculture, Mineral working, Fisheries.

**Comment by mdsimpson42** [comment]
I'm not sure how to do this (just as I couldn't solve #1149).  

There is some code in "api/services/autofill.ts" that queries the database, but I'm not sure how to edit how the text is displayed (#1149) or how to change the order to the specific order stated above. 

It should be relatively easy to rank the options by ID or alphabetically, for example, but specifying the order as above is more complicated. Perhaps we could assign a priority/index value to the table in the database and sort using that instead.

[Will come back to this later, focussing on high-priority tasks]

**Comment by polly64** [comment]
@matkoniecz any thoughts on this one? @mdsimpson42 could you also kindly activate the domestic/non-domestic? question in land use

**Comment by mdsimpson42** [comment]
So, the land uses appear in the same order on the form that they are stored in the database. I can easily, for example, order them by 'description' so they appear in alphabetical order.

Getting them into the order above is more difficult. The values are added in a mixture of different files, so there isn't a single one that I can edit to fix the problem. I could create a script to drop the data from the database and then re-add them in the correct order.

Also, there are some elements listed above that are not in the database (there's no "Residential" or "Residential garden buildings", for example, only "Residential Institutions").

There is a partial list in this file (with others added in other files) https://github.com/colouring-cities/colouring-core/blob/master/migrations/015.bulk_data_sources.up.sql 

---

Is there a list of all these land use options (including the U0XX IDs)? Preferably in a spreadsheet so we can get them in the correct order?

**Comment by polly64** [comment]
On the call now


Polly Hudson
Senior Research Fellow, The Alan Turing Institute
Project Lead:  Colouring Cities Research Programme
https://www.turing.ac.uk/research/research-projects/colouring-london-and-colouring-cities-research-programme

The Alan Turing Institute is the UK's national institute for data science and artificial Intelligence.
The Alan Turing Institute is a limited liability company, registered in England with registered number 09512457 with registered offices at British Library, 96 Euston Road, London, England, NW1 2DB. We are also a charity registered in England with charity number 1162533. DISCLAIMER: Although we have taken reasonable precautions to ensure the completeness and accuracy of this e-mail, transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or be incomplete. If you receive a suspicious or unexpected email from us, or purporting to have been sent on our behalf, particularly containing different bank details, please do not reply to the email, click on any links, open any attachments, or comply with any instructions contained within it. Our Transparency Notice found here - https://www.turing.ac.uk/transparency-notice sets out how and why we collect, store, use and share your personal data and it explains your rights and how to raise concerns with us.

On 26/07/2023, 14:59, "Mike Simpson" ***@***.***> wrote:


So, the land uses appear in the same order on the form that they are stored in the database. I can easily, for example, order them by 'description' so they appear in alphabetical order.

Getting them into the order above is more difficult. The values are added in a mixture of different files, so there isn't a single one that I can edit to fix the problem. I could create a script to drop the data from the database and then re-add them in the correct order.

Also, there are some elements listed above that are not in the database (there's no "Residential" or "Residential garden buildings", for example, only "Residential Institutions").

There is a partial list in this file (with others added in other files) https://github.com/colouring-cities/colouring-core/blob/master/migrations/015.bulk_data_sources.up.sql

________________________________

Is there a list of all these land use options (including the U0XX IDs)? Preferably in a spreadsheet so we can get them in the correct order?
