### ISSUE TITLE
Year of Completion (Planning)

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1197]
From spreadsheet:
(Under "Current planning applications")

- [x] Was the building* completed? 
- [x] If yes, bring up the option to add "Year of completion" and "Source type/link". 

Also:

- [x] Link ~~completion date~~ "Year of completion" to building age.

**Comment by mdsimpson42** [comment]
* - Should this say, "When was the work completed" (or similar)? A planning application might be for extension/renovation, not just building work

**Comment by mdsimpson42** [comment]
Year of completion of... what? It would be good to make this explicitly for the users (as well as for me!)

**Comment by polly64** [comment]
@mdsimpson42 when was the building completed
