### ISSUE TITLE
Location - Footprint ID Source/Links

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1202]
Currently, under "Property/footprint IDs and coordinates" in "Location", the footprint ID, OSM ID and UPRNs have a link underneath them that takes you to the data source.

![image](https://github.com/colouring-cities/colouring-core/assets/21125422/4999ea99-3b34-4e6d-9622-7fe77fea55d4)

While useful, this is different to the "Source type/Source link(s)" format that is used for data sources on other fields on the platform. It was suggested that these be changed to match the other fields, but that the data is prepopulated with the data sources (and is uneditable).

**Comment by mdsimpson42** [comment]
This does mean that the links won't be clickable, which makes it harder to click the link and verify the data. Perhaps we need a better way to click all source links across the whole site? (Separate issue)

**Comment by polly64** [comment]
yes good idea. ok maybe we should leave for moment as we want them to be clickable
