### ISSUE TITLE
Setup with Test Data not Working

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1223]
**The Problem**
As reported by the Montreal team, the setup step to load building data into the app, as part of the "setup a development environment" documentation, no longer works (see "Create a database with test data" in the link below).

https://github.com/colouring-cities/colouring-core/blob/master/docs/setup-dev-environment.md#house-loading-the-building-data

There have been changes to the latest version of the [OSMnx](https://github.com/gboeing/osmnx) library, which is used to generate the footprint data. So, for example, in `etl/get_test_polygons.py`, the code calls the method `footprints_from_point` (line 24), and that function no longer exists. There are also errors with the `plot_footprints` method in that file, which is being given parameters that it is not expecting. 

**Solution(s)**
There are two possible solutions:

- It may be possible to fix this problem and update the code to work with the latest version of `osmnx`, but it does not appear to be a quick fix and will require testing. If we are going to keep this as part of the documentation, we should probably do this at some point.
- Alternatively, we could remove this from the documentation and provide a sample dump file of the data from the colouring London production database that could be used to initially set up the development environment instead.

**Question(s)**
Is this too London-centric a solution? Is it a necessary step in getting the application working? What alternatives could we use to get people up and running when testing with different cities?

**Comment by tomalrussell** [comment]
Hi @mdsimpson42 - this should be a quick fix, see https://github.com/colouring-cities/colouring-core/pull/1224 and osmnx examples at https://github.com/gboeing/osmnx-examples/blob/main/notebooks/10-building-footprints.ipynb

**Comment by tomalrussell** [comment]
The centre point of interest can be changed in the script, if trying to get up and running somewhere else:

https://github.com/colouring-cities/colouring-core/blob/df651521983665056d442603a329a37d966aede1/etl/get_test_polygons.py#L22

**Comment by mdsimpson42** [comment]
Thanks @tomalrussell!

I tried fixing that first function call and then ran into more problems. I wasn't 100% sure how it worked and whether my changes would work, and I didn't really have time to find out as I have other tasks to do before I go on leave/to RSECon. 

As a quick fix, I'm doing a dump of the database from staging, so they've got something to get started with quickly. I'll update the documentation.

Thanks again!!

**Comment by mdsimpson42** [comment]
#1224 build is failing. The previous error message said that osmnx wouldn't work with Python < 3.8, so I changed it to 3.8. Now I'm getting: `Failed building wheel for psycopg2`. I got this error on another project and couldn't work out how to solve it...

**Comment by tomalrussell** [comment]
In general, I would recommend `pip install psycopg2-binary`, which should try installing from pre-built wheels, rather than building against libpq locally. See docs: https://www.psycopg.org/docs/install.html#install-from-source

I've updated a few versions and the build is passing now.

**Comment by mdsimpson42** [comment]
Thanks, Tom! 🙏🏻

**Comment by mdsimpson42** [comment]
I believe this specific bug has now been fixed
