### ISSUE TITLE
OS  and other credits showing on Colouring Bogota

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1228]
Hi Mike here is Bogota link- OS credits etc showing up at bottom of Bogota map - can we create code so partners can add appropriate credits  http://ec2-3-135-71-155.us-east-2.compute.amazonaws.com Hi @mfbenitezp just noticed UK credits showing rather than Colombian ones

**Comment by mdsimpson42** [comment]
The same is true on [Australia](https://sydney.colouringaustralia.org/), showing OS credits. 

Data is included per layer in TSX code files. It could be argued that it should be the responsibility of the local developers to make sure this data is correct. We could add it as a customisable parameter (or at least explain that it needs to be updated in the documentation), but it's going to be different in each country, depending on the technology used/layers shown. 

Neither Bogota or Australia have their code on our GitHub organisation, so I don't think we can add the issue ourselves...

**Comment by polly64** [comment]
@mdsimpson42 thanks, yes it is responsibility of local developers to manage all aspects of their platforms, and yes please add as customisable parameter. Hi @mattnkm and @h-petersen and @mfbenitezp could possibly you add code for Australia and Bogota asap to the repository as soon as possible as it's a core protocol for all institutions working on CCRP code and critical to show we are a networked group -licence terms for code release are here in case you need them https://www.gnu.org/licenses/gpl-faq.html#WhyUseGPL. Also if you could update credits on map interface and add your own once Mike has sorted this the customised parameter that would be great as it's reading as OS which will be a bit confusing for your users.

**Comment by polly64** [comment]
@mdsimpson42 did we do this one?

**Comment by matkoniecz** [comment]
Is it possible that just opened https://github.com/colouring-cities/colouring-core/pull/1297 is fixing this by allowing to configure main attribution

**Comment by mdsimpson42** [comment]
I'd already flagged this as "can't fix", on the basis that this is something the local teams will have to update in their own versions of the code. But I'm happy to close this, accepting Mateusz's (now merged) Pull Request as a solution.
