### ISSUE TITLE
Automatically group age to populate architectural style classes

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1235]
@mdsimpson42 can you crate a link that means any age data is automatically grouped within one of our architectural periods  under 'architectural style - should this be moved to core?

Add new dropdown for source type to all 'inferred from other Colouring dataset'

**Comment by mdsimpson42** [comment]
There are probably two parts to this:

1. We would need to write a database script that we could run that would go through all the existing data in the database. I need to write a similar script for some other issues (including #1174). We have to be careful not to accidentally delete/corrupt any data, but once it's been done for one piece of data, it should be easy to modify it to work on others.

2. It should be relatively simple to add this feature to the interface. It would be similar to the code that automatically calculates the 'land use order' from the 'current land use'. Then any data entered via the interface will automatically fill in that data. It might also be good to find some way to make it clear that that is happening?
