### ISSUE TITLE
add map button under official planning applications

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1241]
@mdsimpson42 add map button under official planning applications as you sometimes can't access this layer of coming from another

**Comment by mdsimpson42** [comment]
Moving to Colouring Core

**Comment by mdsimpson42** [comment]
- Under "Current Planning Applications -> Official Data" I've added a "Click here to view official planning data" button. 
- Under "Past Applications" I've added  two buttons "Click here to view applications from the last 6 months/30 days")
- There was already a button under "Possible future applications"

(It should also be noted that the layers can always be accessed by the selector on the key!)
