### ISSUE TITLE
CSS Not Serving Over NGINX Reverse Proxy

### ISSUE THREAD

**Issue by KoaCWells** [colouring-cities/colouring-core#1251]
**Describe the problem**
As part of the Coloring Montreal project, we have set up our own production server of the Coloring Cities Core and are using an NGINX reverse proxy to view the Coloring Montreal page. For some reason the CSS is not correctly being displayed. Currently, the only way to view the webpage with all the CSS is by setting up an SSH tunnel and forwarding both ports 3000 and 3001. At this point, I am unable to see how it is possible to serve both ports under the same route.

**Expected behavior**
Coloring Montreal page loads with the correct CSS.

**Screenshots**
ColoringMontreal via NGINX proxy
<img width="1076" alt="image" src="https://github.com/colouring-cities/colouring-core/assets/39060964/60104f3c-20af-475e-9220-11f80adbde0e">

ColoringMontreal via SSH tunnel forwarding port 3000 and 3001
<img width="1630" alt="image" src="https://github.com/colouring-cities/colouring-core/assets/39060964/9db3fd80-2ef4-4fdd-b2b8-02d9563ad4f3">

**More information**
This happens in both Edge and Chrome.

**Comment by polly64** [comment]
@mdsimpson42 coukd be prioritise discussion with Concordia on this today? Many thanks

**Comment by KoaCWells** [comment]
I realized that this is not the appropriate way to serve the Coloring Montreal website. I am going to try building the project and using the NGINX to serve the files. I will update you once I have tested it out.

**Comment by matkoniecz** [comment]
It seems like it can be considered as solved and closed then, right? Or is more help needed?

**Comment by KoaCWells** [comment]
Hello @matkoniecz, we have been working on changing the maplayer to use mapbox so this issue has been on hold for the moment. We just tried setting up the colouring-australia repository following the production instructions from colouring-core and for some reason, we are getting a 502 when trying to access the page. We're a bit stumped with both issues at the moment.

**Comment by allanhawas** [comment]
I am not sure @polly64 , maybe @leohatvani can answer the question

**Comment by KoaCWells** [comment]
We were able to resolve the issue by making a few modifications to allow for the use of a subdirectory in the URL. These changes can be seen here: [commit ddfff3f of coloring-montreal](https://github.com/colouring-cities/colouring-core/commit/ddfff3fefff9574414ec40ccf4af4e44bf323db6)

I will create a new issue to explore modifying the cc-config.json or the inclusion of a .env file to account for subdomains and subdirectories such as:

domain.com/subdirectory -> colouringcanada.org/montreal
subdomain.domain.com -> montreal.colouringcanada.org
