### ISSUE TITLE
Interface Tweaks

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1269]
- [x] Location change building name(domestic ) to building name(residential)
- [x] Specific land use -  in box can you edit to say ‘click here to see land use options? Or do you have to type something in – better if not
- [x] ~~Specific land use-  remove ID numbers from box~~ Duplicate of colouring-cities/colouring-london#157 
- [x] Change Type to Type & Form
- [x] Rename dynamic tissue classification – dynamic classification and move to bottom
- [x] colouring-cities/colouring-london#110
- [x] Under ‘Age’ Move Architectural style/Historical period to top
- [x] Under Street Change under green space: to ‘Does this building contain flats and have a dedicated green space?’
- [x] Planning. Change subcategory title ‘land ownership’ to ‘Land ownership type’
- [x] Team- change ‘land ownership’ subtitle to ‘land owner at time of construction’
- [x] Add ‘official’ environmental quality rating to energy performance section
- [x] 13 remove double residential energy rating
- [x] Are there any () irregularities in the shape of the building- remove ‘structural ‘
- [x] Check all info button and remove any that are repeats of questions e.g on construction
- [x] Location – make non residential into a link and remove the name link
- [x] Street Context: Does the building have aback/front garden with greenery?
- [x] Location add ‘open in front of building ID, Unique property ref etc
- [x] Open Longitude building centroid coordinate
- [x] Resilience section: Building damage assessment tool- change to ‘Disaster management tool
- [x] @mdsimpson42 Rename subvisions in 'Location : Property addresses; Building Subvision; Open property IDs & Open Building footprint IDs; Open centroid coordinates for buildings
- [x] as a priority could you restore listed buildings thanks they have got lost
- [x]  source type/links on energy performance (environmental & energy ratings)

TODO:
- [x]  If a building has a Listed Grade in the database, set "is it listed" to yes and ensure link is created to ID

**Comment by mdsimpson42** [comment]
Some of these items have been ticked off because they were addressed by adding new issues.

**Comment by polly64** [comment]
@mdsimpson42 Could you also keep on the list for moment as much easier for me to keep track of and talk to you about - could you put the issue link next to them if they have one and tick on this if completed thanks

**Comment by polly64** [comment]
@mdsimpson42 could you release any changes today so they are there for Monday. Any luck with listed buildings realise I need for meeting on 14th?

**Comment by mdsimpson42** [comment]
I can't find Listed Status anywhere in the code, so I've added it. There is a new question under "Heritage assets and building protection" in Planning that says: "Is the building listed?" and under that, it asks for the Grade and ID (fields which existed in the code but weren't on the interface).

At some point, we should move this out of Core and into Colouring London (see [This Issue](https://github.com/colouring-cities/colouring-london/issues/54)), but for now it was easier to work with what was there.

(What is the difference between this and the "locally listed heritage asset" that we added?)

**Comment by mdsimpson42** [comment]
The current changes are deployed to Staging.

Note: You may have to select "yes" under "is this a listed building?" before you can see the Grade/ID selectors. 

- [ ] I will try and add something to the database script to fill this in automatically if other data has been entered, but I've ran out of time for now.

**Comment by polly64** [comment]
hi @matkoniecz the listed building code you created where you also entered all the IDs seems to have got lost.  We want to show this next week, is there any way you could see if you could reinstall it?

**Comment by matkoniecz** [comment]
it seems to work?
![Peek 2023-11-12 21-52](https://github.com/colouring-cities/colouring-core/assets/899988/d347d2e2-83ae-4082-aa9c-13bba877760d)

**Comment by polly64** [comment]
> hi @matkoniecz the listed building code you created where you also entered all the IDs seems to have got lost. We want to show this next week, is there any way you could see if you could reinstall it?

thanks v much @matkoniecz but are you able to see this on Colouring London? I can't see it

**Comment by matkoniecz** [comment]
@polly64 

looking at it now it seems to work (it fails if you put letters in the id, are there ids with letters in them rather numbers?)

![Peek 2023-11-14 16-20](https://github.com/colouring-cities/colouring-core/assets/899988/ad6e8bcd-f738-4c64-8ebb-7ed02f8ec93e)

**Comment by mdsimpson42** [comment]
Sorry for the confusion. Tom as able to suggest which change to the code apparently removed this feature back in July. There were a lot of changes made at the time so it's hard to see exactly how it was removed (or to remember why). The data and backend code was all still there, it just dropped off the interface, possibly when chances were merged from Core to London. It may have been an accident or it may have been deliberate; I have a vague recollection of trying to rename things so they weren't so UK-specific, but that doesn't explain why it disappeared altogether. 

I'm planning to close this issue for now (in the next couple of days). The fix has been deployed to production ahead of the meeting/demo today. If there are any changes we want to make to these behaviours, we can create a new issue to keep track of them.
