### ISSUE TITLE
react -leaflet library loss issue

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1273]
Concordia has  successfully transitioned to a new map layer using Mapbox GL for launch of Montreal. However, this change resulted in losing the React-Leaflet library and its functionalities. Could anyone possibly make any suggestions for quick resolution for this issue or flag if they have similar? 
@matkoniecz @traveller195 @h-petersen @tomalrussell many thanks

@mdsimpson42 has commented below 

'If code has been deleted or altered, can you recover it using version control? Alternatively, you should all have access to Colouring Cities on GitHub (if not, let me know and I can arrange it). Can you refer to the documentation or the code for Colouring London or the [Core Platform] for help restoring that functionality?

Rather than me trying to remotely debug it over Zoom, it might be easier if you could describe the problems you are having, any error messages you are getting etc. and send me your code. That will probably enable me to find out what is going on more quickly. 

It may be that Mapbox GL is not compatible with the existing system'.

**Comment by demianAdli** [comment]
Hi everyone,

Thank you, @polly64, for bringing the issue to our attention. I want to clarify that we had to disable React-Leaflet because it was overriding some core functionalities of Mapbox. The Leaflet codes are still available. 
I'll update the issue with more details tomorrow.

**Comment by polly64** [comment]
Hi @demianAdli should we close this issue?

**Comment by demianAdli** [comment]
> Hi @demianAdli should we close this issue? 

Hi @polly64 
Yes, this problem has been solved. Thank you for initiating the issue.
