### ISSUE TITLE
Consider different default layer for colouring-core, with UK specific in UK repository

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#1281]
feedback from international meeting: 

setting up https://github.com/colouring-cities/colouring-core outside UK results in blank map, as default OS-based tiles are not existing outside UK

default working globally would be likely better

**Comment by leohatvani** [comment]
Colouring Australia has the largest selection of commented out base maps that I could find: https://github.com/colouring-cities/colouring-australia/blob/main/app/src/frontend/map/layers/city-base-map-layer.tsx
From their selection, OpenStreetMap worked for Sweden, when linked to colouring-core without any issues detected so far.
