### ISSUE TITLE
Add map layer url APIs to and tile render bounding box to config

### ISSUE THREAD

**Issue by Ruben1729** [colouring-cities/colouring-core#1284]
# Problem 
While trying to port colouring-core to the city of Montreal, our team encountered a few problems. These are not documented (at least not in the [dev environment docs](https://github.com/colouring-cities/colouring-core/blob/master/docs/setup-dev-environment.md) or any other docs that we could find).

The map layer does not render outside the UK. Additionally, even after changing the map layers, the buildings do not render outside London.

# Solution
To make it work we had to change 4 files:

In `colouring-core/app/src/frontend/map/layers/city-base-map-layer.tsx` we replaced this
```tsx
const baseUrl = `https://api.os.uk/maps/raster/v1/zxy/${layer}/{z}/{x}/{y}.png?key=${apiKey}`;
```
with
```tsx
const baseUrl = `https://a.tile.openstreetmap.org/{z}/{x}/{y}.png`;
```

In `colouring-core/app/src/frontend/map/layers/historic-map-layer.tsx` we replaced this
```tsx
<TileLayer url="https://mapseries-tilesets.s3.amazonaws.com/london_1890s/{z}/{x}/{y}.png" />
```
with
```tsx
<TileLayer url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png" />
```

In `colouring-core/app/src/frontend/map/layers/historic-data-layer.tsx` we replaced this
```tsx
<TileLayer url="https://mapseries-tilesets.s3.amazonaws.com/london_1890s/{z}/{x}/{y}.png" />
```
with
```tsx
<TileLayer  url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"/>
```

In `colouring-core/app/src/tiles/rendererDefinition.ts` we replaced this
```ts
const EXTENT_BBOX: BoundingBox = [-61149.622628, 6667754.851372, 37183, 6744803.375884];
```
with
```ts
// Montreal bounding box
const EXTENT_BBOX: BoundingBox = [-8135086.254447, 5675540.368758, -8267367.825970, 5751427.756290];
```

It would be useful to update the [configuring-colouring-cities.md](https://github.com/colouring-cities/colouring-core/blob/master/docs/configuring-colouring-cities.md) to describe how to change the bounding box and map layer URLs.

# Alternatives
Update the config file to account for these links as well as the bounding box to allow developers to easily change the map layer API and bounding box to fit their city.

**Comment by matkoniecz** [comment]
Note that if we switch to using OSMF tile servers in default we should make users of code aware that they need to follow https://operations.osmfoundation.org/policies/tiles/ - and ensure that it is followed in default setup (including attribution)

**Comment by matkoniecz** [comment]
BTW, nowadays `https://tile.openstreetmap.org/{z}/{x}/{y}.png` is better than deprecated `https://a.tile.openstreetmap.org/{z}/{x}/{y}.png`  - see https://github.com/openstreetmap/operations/issues/737

**Comment by matkoniecz** [comment]
And thanks for creating this issue! It is helpful to have feedback like this.
