### ISSUE TITLE
Remove London-specific text on Contact page

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1285]

**Comment by matkoniecz** [comment]
https://colouring.london/contact.html - it is about 

>  You can send us comments or ask questions on our discussion threads at https://discuss.colouring.london/.

right?

**Comment by mdsimpson42** [comment]
No, I'd already fixed it, I was just keeping track of things and/or trying to organise and close a load of issues before Xmas. I just noticed some London-specific text in the Colouring Core repo, but I've already updated it.
