### ISSUE TITLE
Neuroaesthetic features - Stage 2

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1331]
- [x] Make the blue map button visible under hominess (all sections) when active. Non-interactive, greyed out but "showing building hominess".
- [x] Hide 'average neuroaesthetic score' - Check with Penn they don't want this.
- [ ] #1362
- [x] Remove "thank you for your feedback" box. Add phrase to the red "please note" box.
- [x] Change "feel to you" to "make you feel"
- [x] Your score: "Not yet entered". 
- [x] Average: "Average score", "two voteRS"
- [x] "Worth keeping" - make consistent.
- [x] "Hominess", "Coherence", "Fascination" in bold. Make titles, then have questions.
- [x] One category: Buildings & Streetscapes (Hominess -> Building & Streetscape. etc.)
- [x] At the top: "This section collects data on what you feel about the exterior of a building and the surrounding streetscape."
- [x] Change "Are your answers..." one box, at the top. "Please select an option below that best describes how well you know the building"
- [x] Remove the "Please note..." box, pop-up a message if you haven't filled it in.
- [x] Check if public/community ownership is connected to field on Planning (if not, connect).
- [x] 'Please tick here if data is being entered as part of a school project'  put at very end

**Comment by mdsimpson42** [comment]
The Neuroaesthetic features are in the Core platform, so I've moved this issue to the Core Repo.

**Comment by mdsimpson42** [comment]
I've been looking at the Confetti but haven't yet found an easy way to fit it into the existing code. When do we want the confetti to appear? When they click "save edits" (if so, it would be on all categories, not just community)?

**Comment by polly64** [comment]
@mdsimpson42 hi mike, can you try a couple of options for us to look at?

**Comment by mdsimpson42** [comment]
- [ ] "How well do you know this building & streetscape?"
- [ ] Dropdown: change to: "Local Knowledge", "Professional Interest", "Seeing an Image"
- [ ] Do you have any other comments on this type of building/streetscape?
- [ ] "I think this because..." -> "I think that..."
- [ ] "Please tick here if you are entering this data as part of a school project?" (remove yes)
- [ ] Increase text size in "here we are collecting..." box
- [ ] "If not" and "if in" questions only when you select Yes or No to the first question.
- [ ] Check colour loading - current zoom level doesn't update?
- [ ] Remove average colours from the key
- [ ] Trigger confetti on "how well do you know" and "type of building/streetscape"

**Comment by mdsimpson42** [comment]
I've been playing with a few ways to increase the range between the highest and lowest values on the scales to make the difference between values clearer.

![image](https://github.com/colouring-cities/colouring-core/assets/21125422/c1c09d92-b7e3-49b5-8f28-c41c7ece83f1)

1. The one we're currently using. 
2. Lowering the saturation with each step. 
3. Increase the saturation. 
4. The same as 3 but with a grey instead of white. 
5. The middle colour is the bright green, and adjust the hue and brightness from there.

Personally, I think 2 and 5 make the most sense, both aesthetically and in terms of representing an increase in the value with each step. (4 also makes sense, but the grey is kinda ugly and hard to distinguish from the background colour in dark mode.)

I'm not sure what the best option is, given that it was important that the colours be bright and engaging. Should we discuss the options with Penn?

**Comment by polly64** [comment]
Hi @mdsimpson42  thanks, I think the dark green might get lost if people have dark background on. I think let'd go for number 3 . could you send the other 3 options too

**Comment by mdsimpson42** [comment]
Here's a wider range, it possibly is slightly clearer if you either start in the middle with the bright green and work down or up the scale?

https://hihayk.github.io/scale/#4/4/99/99/0/0/100/-100/00d924/0/217/36/white

![image](https://github.com/colouring-cities/colouring-core/assets/21125422/06386f28-5ef1-40f7-898b-f9db55452200)

**Comment by polly64** [comment]
@mdsimpson42 thanks mike
- I like the difference in two greens in hominess 
- can u change the streetscape blue to be more turquoise - think too similar to building colour
- can you add a bit of orange to streetscape purple  - again to just make user feel it is a different  brighter colour they are putting in.
- I think the brightest one should be 5
- I think 1 should be cream not white - so different from white default on 'daytime'
- can we try making number 2 for each one a bit paler, and 5 for each  one a little darker or more saturated - and then adjust middle ones and then we'll just leave 
-  I'll add a lot of entries on staging to just to see what it looks like en mass
- is the database error ok now?
see you at 4

**Comment by mdsimpson42** [comment]
I'm struggling to get the confetti burst to work, so I'm going to create that as a separate issue and close this one. Any new changes to the neuroaesthetic features can be added to a new issue.
