### ISSUE TITLE
Performance: Data layers

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1340]
Layer issues – need to be able to manage multiple nested layers. @matkoniecz  is currently adding code for adding transport, admin boundaries, and statistical geography layer options now feels we need to urgently need relook at the way these are structured @Polly Hudson, here we could help. You can already assign it to us)
[https://github.com/colouring-cities/colouring-core/issues/1334]

**Comment by MKIM1008** [comment]
@mdsimpson42 contacted me last week to add the layers,too.
