### ISSUE TITLE
Fix Menu Links

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1382]
Some of the links in the menu of the core platform do not work, presumably because the Wiki pages have been renamed. Correct them so that all of the links direct to valid sites.

![image](https://github.com/colouring-cities/colouring-core/assets/21125422/5ff57717-638f-4d64-9ebd-cbfad4be7e68)

**Comment by mdsimpson42** [comment]
@polly64 I've corrected most of the links. I have a couple of questions:

1. The "Code of Conduct" link goes to a page on the platform itself (i.e. https://colouringbritain.org/code-of-conduct.html) rather than the Wiki. Is that correct, or should it also link to the Wiki?

2. Same as above for "Ordnance Survey terms of UPRN usage". Should that be moved to the Wiki? You mentioned renaming this to "Building Footprint Terms of Usage. But do we need a Britain-specific page for the Ordnance Survey details?

3. Same for the "Contact" page, should that link to somewhere central like the Wiki?

If we redirect those pages to the Wiki, we can remove them from the platform. Alternatively, we can leave them on the platform if we think that countries might want to add their own info to these pages (Contact details, for example)


Note: this is on the Core Platform, so only links that should be in all versions - there is a separate issue for Britain-specific links.

**Comment by matkoniecz** [comment]
see also https://github.com/colouring-cities/colouring-britain/issues/309

**Comment by mdsimpson42** [comment]
I've updated all of the URLs so they now link to the correct pages on the manual/wiki (and removed the old pages from the site).
