### ISSUE TITLE
Geolocation button

### ISSUE THREAD

**Issue by tomalrussell** [colouring-cities/colouring-core#139]
Add button to map interface which zooms to current position

Use case: I'm out and about and want to edit the building I'm stood by, interface jumps me to this position on the map.

Leaflet geolocation plugins: https://leafletjs.com/plugins.html#geolocation - at a quick glance, [domoritz/leaflet-locatecontrol](https://github.com/domoritz/leaflet-locatecontrol) ([demo](https://www.domoritz.de/leaflet-locatecontrol/demo/)) looks good.

**Comment by tomalrussell** [comment]
Use case: I'm out and about and want to edit the building I'm stood by, interface jumps me to this position on the map.

Leaflet geolocation plugins: https://leafletjs.com/plugins.html#geolocation - at a quick glance, [domoritz/leaflet-locatecontrol](https://github.com/domoritz/leaflet-locatecontrol) ([demo](https://www.domoritz.de/leaflet-locatecontrol/demo/)) looks good.

**Comment by traveller195** [comment]
hi everybody,
I/ we (from Dresden) support the initial idea to add an geolocation button for the current location (moving the map to current location as center point)
ans also - to keep it simple - without an automatically follow-mode. So it could be enough, to just manually press this button to refresh the current position.

From OpenLayers I already know its geolocation function. Leaflet should be similar. 

If I have some time (maybe in March 2023) I could implement it. If one of you @tomalrussell @matkoniecz have time for it earlier, then give an sign ;-)
Our launch event for Colouring Dresden is on 6th March, so it would also nice to have most of planned features working. 
best,

**Comment by matkoniecz** [comment]
I am definitely not working on it and it would be extreme coincidence if after over 4 years someone would be working on it right now, so I guess that you are free to make a PR.
