### ISSUE TITLE
Upload script used to import building footprints into the database

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1421]
~~@mdsimpson42 can you add script that Kenya referred needed for set-up and add info on where it is a located thanks~~

There is an SQL script which was used in Colouring Britain to upload the footprints. Mateusz sent it to me, and I used it to create the Colouring Singapore prototype. This script should be uploaded into one of the repositories (i.e. https://github.com/colouring-cities/colouring-core-config) and linked to in the setup documentation.

**Comment by mdsimpson42** [comment]
I'm currently modifying the script to make it more user-friendly and customisable. I will do another pass through it and then check it in as a first draft. It will likely require additional development, customisation and documentation to help others use it.
