### ISSUE TITLE
Formatting of titles

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#1425]
spotted in https://github.com/colouring-cities/colouring-britain/issues/376

we have

> General Land Use

but

> Specific land use(s)

we have

> Architectural style/historical period
> Building age/construction date
> Cladding, extensions and retrofits
> Lifespan and site history
> Survival tracking
> Historical map data options

but

> Energy Performance
> Energy Systems

and

> Design / Team

we have

> Green walls/roof
> Green Space
> Flood zones

Maybe "Green Space" should be "Green space"? And "General Land Use" turned to "General land use" for consistency?

@polly64

**Comment by polly64** [comment]
@matkoniecz thanks I think we should use capital for these titles unless for 'of'

**Comment by matkoniecz** [comment]
so also say "Number of Floors/Storeys" ? or "Number of Floors/storeys"?

**Comment by matkoniecz** [comment]
Also "Incomplete/Missing Data" and "Street/Pavement" I see also "Design / Team". There is also "Open Property IDs/Footprint IDs", "Base Building Footprints/Polygons Used For Data Collation, Verification And Visualisation", "Building in Community Use / Ownership", "Architectural Style/Historical Period", "Building Age/Construction Date", "Green Walls/Roof"

Should it be "Heritage Assets and Building Protection" (is "and" in the same class as "of")? Also "Resilience Indicators and Risk Assessment", "Cladding, Extensions and Retrofits", "Lifespan and Site History", "Constructions and Demolitions on This Site"

What about "at"? Is "Land Ownership At Time of Construction" OK?

in: "Building in Community Use / Ownership" or "Building In Community Use / Ownership"?

on: "Constructions and Demolitions on This Site"

**Comment by polly64** [comment]
@matkoniecz Should it be "Heritage Assets and Building Protection" (is "and" in the same class as "of")? 

Yes

Also "Resilience Indicators and Risk Assessment", "Cladding, Extensions and Retrofits", "Lifespan and Site History", "Constructions and Demolitions on This Site"

Yes

What about "at"? Is "Land Ownership At Time of Construction" OK?

No , can you make 'at' and 'of' small please


in: "Building in Community Use / Ownership" 

Yes

or "Building In Community Use / Ownership"?

on: "Constructions and Demolitions on This Site"
 "Constructions and Demolitions on this site"
