### ISSUE TITLE
Listed buildings and conservation area data

### ISSUE THREAD

**Issue by urbandataanalysts** [colouring-cities/colouring-core#160]
@Polly64 Two questions for you. Along with the fields on the control page do we also want to add the date the building was listed? Similarly conservation areas also have a delegation date when they came into force which we can include if you'd like?

For boroughs who haven't released their conservation area data this won't be that visually obvious we'd need to flag the buildings in the borough to not colour or add overlay. One to discuss. 

@tomalrussell I'll also include the listed building list entry number, this can then be used to generate the URL to the entry as below;

List entry number : **1026593**
URL is this plus standard stub
https://historicengland.org.uk/listing/the-list/list-entry/1026593

For the energy project we are doing this in the js, what would you like to do here? I can generate the links in SQL and have them in db or we can generate them OTF from the number

**Comment by polly64** [comment]
1) Yes please, designation dates for both will be very useful for future analysis.
let talk re encouraging borough uploads re CA data. 
2) As soon as CA data are  visualised we can write to the missing at in a single email.
3) Can we put constraints on URL entry format ie can you say it always has to have the historic england prefix and then include a numeric ID as these will always be the same?

**Comment by tomalrussell** [comment]
For anything where a URL can be generated from ID or similar, just the ID would be ideal - generating links on the fly should be safer and simpler.

**Comment by polly64** [comment]
Dom could you have a think how data sources would work in the Planning system?  We need to try and get this on as soon as we can.  Tom presumably if someone edits something then the source box will clear too for them to put new source in?

**Comment by urbandataanalysts** [comment]
@polly64 I'm not sure I've fully understood the query, is this to think what people might do with the data? I've lost track on a few items below;

### What level of editing are we allowing on statutory designated items (Listed buildings / Conservation areas)? 
I think when we last spoke we discussed allowing people to flag if they thought it was incorrect perhaps they could also have a free text box in which to suggest source or reason but this data is hidden. I think the risk of someone maliciously editing is lower than an accidental deletion/edit. 

### Data source versus input user
The source should read Historic England for listed buildings and the borough name for conservation areas. Unfortunately for the conservation areas there's no consistent URL for where these come from so we'd have to manually search and input per borough, this would then have to be maintained by us if the borough changes their website. There seems to be a bit of a crossover between source and user, if we want to motivate borough teams to input data then do we want to also list them as the user who's added the data, this would also provide another layer of validation ie. The public would see a conservation area in RBKC provided by RBKC and last edited by RKBC if last edit was by A.N.User then it would be obvious there was more of a risk on data accuracy for that area?

**Comment by polly64** [comment]
@mz8i @MeldaS just to also send u this older thread
