### ISSUE TITLE
Link buildings to more aggregate OS polygons

### ISSUE THREAD

**Issue by tomalrussell** [colouring-cities/colouring-core#170]
As suggested by @urbandataanalysts in the context of #163 

Data aggregation
- e.g. associating buildings, which are basically one-to-one with Ordance Survey MasterMap building polygons (TOIDs) with the more aggregate OS Local/District block polygons.

Another motivation - associating buildings with an (open data) block-level polygon could be a really useful bit of work towards making the dataset user-friendly, could support other uses and visualisations that might end up in the showcase, etc...

**Comment by polly64** [comment]
s

**Comment by polly64** [comment]
See work on Colouring Loughborough EPCs
