### ISSUE TITLE
Assign building street names from open data

### ISSUE THREAD

**Issue by tomalrussell** [colouring-cities/colouring-core#184]
Look into OS Open Roads, nominatim or similar to populate building street names with spatial analysis 
- nearest-line-to-polygon or centroid should catch many cases
- street-corner-cases (prefer main road?)

**Comment by polly64** [comment]
need to start trying to open this up asap as links with the age field as people want to add name of institutions churches erc. But feel this really needs a delay on it initially so can be moderated - until other features suggested are progressed

**Comment by dominijk** [comment]
We have sources for many publicly accessible buildings (non-domestic / institutional). Subject to a licence check we could potentially add a lot of these via bulk upload. This would leave domestic buildings which make up the majority of the stock to complete by other means.
