### ISSUE TITLE
Show date and username of last edit under each field

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#269]
- [ ] Last edit date
- [ ] Last edit by

**Comment by mz8i** [comment]
I can take a stab at this, but I feel we should be careful about putting too much information on the basic screen. If anything, I'd suggest having a "View history" button and the last edit visible only upon user clicking this button. What do you think @tomalrussell ?

**Comment by tomalrussell** [comment]
I think this could fit okay:

![image](https://user-images.githubusercontent.com/2762769/68663453-98e8fc00-0536-11ea-94ed-dcf56abf30be.png)

- though should probably use simple date format (no real need for the "6 days ago")

**Comment by edwardchalstrey1** [comment]
Make last edit date more visible
