### ISSUE TITLE
UX: Go to day

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#310]
From excel list, @polly64 what is this one? 

> Go to day automatically in edit mode

**Comment by tomalrussell** [comment]
This is referring to the light basemap ('day' mode), which can be triggered by clicking the 'Switch theme (light/night)' button (top right corner of the map, under the zoom buttons).

It's easier to read street names and see some underlying detail, so should help with editing.

**Comment by tomalrussell** [comment]
See #129
