### ISSUE TITLE
UI/UX: Community showcase 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#340]
- [ ] Contact Jamie for content to populate first showcase 
- [ ] Mock up Show case page with 2 examples (if time)

Initial layout for showcase page to share uses of Colouring London data:
- [ ] Title/image/attribution/description
- [ ] search by tag (subject) to filter items displayed

use original design (2017):

![showcase](https://user-images.githubusercontent.com/42236514/62830997-3b2fd580-bc10-11e9-8b74-3d6780ed2d3d.JPG)

**Comment by mdsimpson42** [comment]
We discussed this during a meeting today. We want to set up a separate site, as a subdomain of colouringcities.org, that looks/behaves something like this: https://www.turing.ac.uk/research/project-status/ongoing

**Comment by mdsimpson42** [comment]
Closing this, as we now have a duplicate issue for developing a prototype showcase #1233
