### ISSUE TITLE
db: Add Construction/Materials category to database

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#361]
**Fields for launch**
- Construction method > Single option autocomplete/drop down
- Primary material > Single option autocomplete/drop down
- Secondary material > Single option autocomplete/drop down (repeats primary)
- Primary roofing material > Single option autocomplete/drop down
- Secondary roofing material > Single option autocomplete/drop down (repeats primary)

**Steps for adding new fields to database;**

- [ ] Identify bulk data sources (optional)
- [x] Required - Define field values as static category page
- [ ] Required - Identify need for source and verification for fields, log to spreadsheet
- [ ] Required - Define input method for field (Drop down / Autocomplete / Free text) 
- [ ] Required - Add category down file
- [ ] Required - Add category up file
- [ ] Optional - Create nudge function (might be post launch) for linked fields as linked issue

On completion set up Github issue for activating fields on front end

**Comment by MeldaS** [comment]
@polly64 I'm getting the code ready to launch the construction category. Just to confirm, you'd like to launch with just core_construction_material? 

If so, could you confirm / provide info for the following:

**Data field setting** -> Single option autocomplete/drop down (Basically a drop down menu with the list of materials. If users type directly into the box, suggested autocompleted text will appear). I think this is the ideal setting for Core Materials.

**List of materials:** (taken from issue #539)
- Wood #96613b
- Stone #ffffe3
- Brick #f5d96b
- Steel #beffe8
- Reinforced Concrete #fca89d
- Other metal #5c8970
- Other natural material #b5a859
- Other man-made material #c48a85

**Editable** -> should it be editable to the public? I would say yes. 

**Tool Tip** -> The little "i" button that provides info when you click on it. Could you help write the statement? Maybe something explaining that the core material is not necessarily the most prevalent one on the facade (if that's true). Or anything else that you think should be mentioned. 
"This is the core construction material of this building. xxx"


These are other data fields that we could also launch under the construction category. We could have them visible but not yet editable. Or just launch them and make the editable. If you'd like to launch any of the below, then we need to provide all the info above for each of the below. Here are my thoughts on each. 

- _Construction method_ > MS: I don't have any data to upload for this. Not sure if anyone else does.
- _Secondary material_ > MS: In the HE dataset on listed buildings, there are many secondary materials that we can list, but we'd need to think about if only one secondary material can be listed, or if we should allow users to select several from a list (my suggested option), or some sort of free text with validation (not sure how this would work)
- _Primary roofing material_ > MS: We have a lot of covering material data in the HE dataset, but we'd need to go through together and make sure they all make sense. We could launch this data field then populate it later. 
- _Secondary roofing material_ > MS: Also an option, but I haven't seen many buildings with two roofing materials.

**Comment by polly64** [comment]
@MeldaS thanks

1. Yes Title is 'Core construction material'
2. Yes dropdown correct
3. Yes should be editable
4. Information button to stay something like ' Here we are collecting main structural material' or 'This means main structural material'
5. a)  Construction method - omit as core construction material replaces this
   b) 'Secondary construction material/s'- use tick list
   c) 'Main roof covering'
   Slate
   Clay tile
   Wood
   Asphalt
   Iron or Steel
   Concrete/Cement
   Other metal
   Other natural material
   Other manmade material
   c) Secondary roofing material omit.
 
Attach amended execl file below- not 100% sure on some and 20 or so on weatherboarding list needs checking but let's upload and we can correct later.
[NonNull_London_LBs_17Sept2018_3_matched_v1 Polly revisions march 24.xlsx](https://github.com/tomalrussell/colouring-london/files/4389644/NonNull_London_LBs_17Sept2018_3_matched_v1.Polly.revisions.march.24.xlsx)
