### ISSUE TITLE
TEAM category

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#406]
Links to #362,cross ref awards #351 still to confirm remaining fields. Original suggestions;

- Original building architect
- Original building engineer
- Original building contractor
- Original building developer

**Steps for adding new fields to database;**

- [ ] Identify bulk data sources (optional)
- [ ] Required - Define field values (free text) 
- [ ] Required - Identify need for source and verification for fields, log to spreadsheet
- [ ] Required - Define input method for field (as existing source button) 
- [ ] Required - Add category down file, naming convention is original file name plus `-extra` as https://github.com/tomalrussell/colouring-london/pull/389
- [ ] Required - Add category up file
- [ ] Required - If not all fields added create new issue and link, copy steps above 
- [ ] On completion set up Github issue for activating fields on front end

**Comment by polly64** [comment]
Hi, have just been given some amazing data for 19th builders in Dartmouth Park Camden  which will be a great first input. 

I have worked through categories again. Can we adjust current categories before release to following (Dom I can talk this through with you tomorrow).

Line 1 = 2 boxes  Choose  'Developer (Speculative builder)- relevant to 18th/19th development e,g individual builder's name John Jones' 'OR'  'Developer (non-builder) say Carillion, London Borough of Hackney, Peabody, Barrett Homes etc
(Where the former the only other box that is likely to be filled is  ' Design source' below - and the drop down should include pattern books, other (am checking these with Survey of London )
Line 2 = 2 boxes  Choose 'Architect' 'OR' '  'Design Source'
Line 3 = Where applicable - Main Contractor, Engineer, Other contractors (where applicable)- This will only apply to a small percent buildings so shouldn't take up too much space
Line 4 = Source/s
Line 5 = Links to relevant websites (as for Age)
Plus Edit history and verification button

**Comment by polly64** [comment]
June 2020 to do list


Historical links #407

**Comment by polly64** [comment]
@mz8i Subcats: 

Team

1. [ ]  Add Note to contributor in coloured box (as for land use)
'Can you help us add information on who built the current building or major extension to it ?'

2. [ ] Do you wish to add information on a) the main building  b) a significant  extension

3.  [ ] When was the work carried out (Year)

4.  [ ] Who was the building developer? 

5. [ ] Who was the building designer? - Choose from dropdown
i) Speculative builder/developer 
ii) Professional architect  (first, second name)
iii) Engineer (first, second name)
iv) Landowner/amateur architect (title, name, surname)
v) Pattern book design (Title, Author, Date)  
vi) State design (i.e. board school) (Originator, building type) 
vii) Volume housebuilder design  (Developer, building type)
viii) Other

6. [ ] Additional relevant team members 
a) Add Role, b) Add company or individual name

7. [ ] Add links to relevant websites

8. [ ] Has the building ever won a prize? if so add link (do not worry about activating this yet)
