### ISSUE TITLE
UI/UX: Education page links 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#422]
Via email from A.Dennett  13th September 2019;

Action points from the meeting were:
**For launch**
- [ ]  1. CL team to put an ‘Education’ placeholder tab on the colouringlondon.org site 
- [ ] Create flier on static page linked to Education tab 
 **Post launch**
- [ ] Resolve branding on flier

@polly64 As above this is now an issued logged to the system for action

**Comment by polly64** [comment]
*   just to confirm  they want the page and flier on for launch. The issue for after the launch is the branding as not time to do before but essential


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by polly64** [comment]
Pause on this

**Comment by polly64** [comment]
Keep on hold until further discussion with Colouring London education partners
