### ISSUE TITLE
UI/UX: Community category - Activate maps/join with Like me?

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#433]
**Dependencies**
Run  migrations as #432 to enable input to db

**What UI does**
Allows input for three fields in category as below, allows multi copy;
- Ownership type - drop down from 5 choices 
  - Private individual 
  - Private company 
  - Private offshore ownership 
  - Publicly owned 
  - Institutionally owned 
 - Ownership perception - Yes/No option
 - Historic ownership - Yes/No option

**What map looks like**
On load, category visualisation is ownership type. Initial colours as below;
- Private individual -  `#aaaaaa`
- Private company - `#f2a2b9`
- Private offshore ownership - `#ab8fb0`
- Publicly owned -`#57c28e`
- Institutionally owned - `#6bb1e3`

Remaining categories should overlay onto this. Ie hatch or symbol so you can visualise the current state and either/or of the others. @tomalrussell i'm new to mapnik would this mean adding a layer with transparent background or would it render a new tile with colour and symbol.

**Comment by polly64** [comment]
Pause on this as will be merged with like me?

**Comment by dominijk** [comment]
@polly64 Can you confirm this and provide a bit more on how this will work and what it would look like? This is one of the categories that the work is largely completed on so could go live without much further work.

**Comment by polly64** [comment]
Hi Dom I think we've got too a bit much on the private ownership side.  Though we need to support and stimulate work in this area  the issue of ownership can be absorbed at a later date as discussion - which is being advancedas you've identified -at the moment opens these data up even more and allows us to absorb them more easily. We need to be v careful about a) distracting from all the other areas of the project and dragging CL into a political discussions. We know this is a prime target for heated media debate. Our main messages  need to be crystal clear to users that a) user and building owner privacy is paramount, b) our work is simply about collating visualising and generating data that are as accurate as possible in a format that can be used in  scientific analysis of the city/advancing research into its sustainability. I think by separating out private at the moment we are crossing over the privacy line. 

I can totally see why the data are important in analysis but I just think at the moment we need keep with your original idea of assuming it is all private and asking which ones are community/state owned only. We can subdivide at a later date but this needs much more consultation and discussion. Under Team we will be collecting historical ownership of sites so we will collect a lot of interesting data here. 

As we now have the Dynamics section being introduced we need to remove the Community category. I'd like to therefore try test this the community assets section under the Like me? Paul directed me to the current government  'keep it in the community' campaign so these link nicely. Also can you try and access Government property Unity for national assets.  

So my suggestion is to call the category Like me? still and rename the subtitle Local asset? perhaps.  I think it is still possible we may need to limit Like me to non-residential

**Comment by dominijk** [comment]
@polly64 Given that having two visualisations within a category is a bigger change. For now/Paris are we keeping the Like me category and community category as they are? I think the changes suggest in 1 - 3 are good. I think 4 needs further discussion but I'd be keen to resolve this soon as it interweaves with landuse to some extent > I've move that discussion to slack.

**Comment by polly64** [comment]
Yes good idea.  Ok: 
a) Let's visualise Like me as now (only one to be visualised at present)
b) start collecting questions 1-3 asap
c) talk more about question 4
