### ISSUE TITLE
UI/UX: Add data source 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#492]
**Initial sketch for this** 
Objective: To add source where we want to collect this. To show source that we have to help users make decisions on when and where to edit. 

Links to: Verification colouring-cities/colouring-core#305 colouring-cities/colouring-core#263 colouring-cities/colouring-core#199 
Dependent on: colouring-cities/colouring-core#396 colouring-cities/colouring-london#79 

**How this looks - viewing**
Focus remains on the data field with data source surfaced and visible. Updating the data updates/removes the source. To edit the source you must edit the field. A field maybe be enter without a source but a source can't exist with data. Clicking the verify button verifies the field and the source linked to that field, after click count of verification increases (n+1) 

<img width="498" alt="Screen Shot 2019-11-07 at 17 03 59" src="https://user-images.githubusercontent.com/6041913/68410659-fcfb7100-0180-11ea-8c6b-265b7b06b424.png">

**How this looks - editting**
1. Users clicks on field, boxes for source appear with prompt for user to complete.
<img width="505" alt="Screen Shot 2019-11-07 at 17 12 35" src="https://user-images.githubusercontent.com/6041913/68411142-d38f1500-0181-11ea-9254-efe85de85594.png">
2. Move to next field or save and close

@tomalrussell @mz8i Can I get your comments on this

**Comment by polly64** [comment]
Re source categories to collect 
Tier 1 | Tier 2 |  
-- | -- | --
  |   |  
Local knowledge | n/a |  
Assessment by eye | Professional | n/a
  | Non-expert | n/a
Book | Title, First author, Date, Weblink |  
Other publication | Publisher, Title, First author, Date, Weblink |  
Map | Publisher, Date, Location, Weblink |  
Historical Image/ archive document | Type of document, Date, Location |  
Film | Title, Date and Weblink |  
Database | Title, Location, Weblink |  
Specialist Website |   |  
Other |   |
