### ISSUE TITLE
UX/UI: TBC Add URL link to Discourse channel for category suggestions and feedback

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#533]
For each category add link that explains to users how they can give feedback on the fields we collect in a given category. 

**Perquisites**
Create `Topics` for each of the categories within the Data collection [Topic](https://discuss.colouring.london/c/data-collection) (@tomalrussell is that the correct terminology / approach?). 

Links to adding Discourse notifications to Slack

**Comment by tomalrussell** [comment]
Yes, sounds right to me - each of the Colouring London data categories (Location, Age, etc.) gets a "topic" (discussion thread), and they're grouped under the Data Collection "category".
