### ISSUE TITLE
PLANNING & DESIGNATED BUILDINGS

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#538]
@mz8i To do list - PH still to complete

1- [ ] Tidy up by Concertinering all duplicate options i.e. don't show more details for GHLER, listing etc  until 'Yes' option has been clicked

Check these with PH colouring-cities/colouring-core#574

---- 

Update to planning category to switch map visualisation from conservation areas (as current) to listed and protected buildings:

Linked issues colouring-cities/colouring-core#300 colouring-cities/colouring-core#232 colouring-cities/colouring-core#160 

- Switch from single field categorisation to multi-field categorisation
  - `planning_in_conservation_area` - If true colour as below below else don't render
  - `planning_list_cat` - visualised if `Listed building` null (use grade as below), else if `Scheduled Monument` use colour below - No data added see [issue](https://github.com/colouring-london/colouring_london_analysis/issues/16)
  - `planning_list_grade` -   visualised as below colours/categories
  - `planning_in_local_list` - If true colour as below else don't render - Data added see [issue](https://github.com/colouring-london/colouring_london_analysis/issues/15) 
- On category load expand to show `Listing and protections` ? Team discus
- Lock front end entry for `National Heritage List for England list id`, `National Heritage List for England list type
` , `Listing grade` and `Is listed on the National Heritage List for England?` 
- ~~Update basemap  to include conservation areas see colouring-cities/colouring-core#242~~ 
- Add verification box to front end (disabled)
- Add disclaimer to legend and below sub title that the only authoritative source of listed buildings data is HE and not to rely on CL data for list status or extent of listing
Disclaimer text: "_All data relating to designated buildings should be checked on the National Heritage List for England or local authority websites where used for planning or development purposes_"
- Add new legend for visualisation as below colours 
Prepopulate NHLE links colouring-cities/colouring-core#354
Discussion on boundary lines colouring-cities/colouring-core#242
Mapping planning applications -post June 2019 colouring-cities/colouring-core#211

Colour key  references for Grade 1, Grade 11*, Grade 2 and locally listed buildings

name | rgb | hex
--- | --- | ---
Grade 1 (Red)  | `rgb(199,46,8)` | `#c72e08`
Grade 11* (Gold)  | `rgb(230,152,0)` | `#e69800`
Grade 11  (Grey/Blue)  | `rgb(158,187,201)` | `#9ebbc9`
Locally listed  (Pink) - Data in staging and production for Lambeth | `rgb(255,190,161)` | `#ffbea1`
Scheduled monuments (White with lightweight black outline)  | `rgb(255,255,255)` | `#ffffff`
Building in conservation area | `rgb(170,170,170)` | `#aaaaaa` |

Dom can we test these as soon as you're ready as we need to check quantities of colour for London (LB's as as a whole).  Also Do we have access to any local lists we can test? If not will try and find some.

**Comment by dominijk** [comment]
@mz8i I think I'm right in understanding that we don't currently visualise listed buildings but we have discussed changing the Planning category to use this in place of the current layer

**Comment by polly64** [comment]
Yes that's right- but  in the end we will want options for several maps in a category though this can be after March

**Comment by dominijk** [comment]
@polly64 Ok, can we confirm that until we have that option we want to use listed buildings (as #475 ) to visualise this category or are we keeping conservation areas (as current)?

**Comment by polly64** [comment]
Yes we need to visualise listed buildings over conservation so would like to proceed this asap but if we get more help would definitely like to look at  integrating conservation data area into same map. V important as as well as indicating areas of historic/arch significance CAs also pinpoint specific areas where development pace/metabolism is being deliberately slowed and where incremental development/adaptive reuse is likely to be occurring.

**Comment by polly64** [comment]
realise we will also need to put a fine black border around scheduled monuments as white will only show on black, not white, background

**Comment by polly64** [comment]
dom let me know what you need me to do in terms of collating locally listed building datasets. Here are download links for lambeth and hackney- would be good to get data for these boroughs at least- initially- let me know how easy these are to uplaod .
http://lambethopenmappingdata-lambethcouncil.opendata.arcgis.com/datasets/e304f6fb73574e00ae1d2493092f0d61_6?geometry=-0.129%2C51.456%2C-0.099%2C51.466 or https://data.gov.uk/dataset/f55dcd6a-15d3-4c67-b1bc-04d73252e71f/locally-listed-buildings
https://data.gov.uk/dataset/f3a6bfd3-8e42-4a22-94dd-6f02b9d431ed/hackney-locally-listed-buildings

**Comment by dominijk** [comment]
The challenge on this issue is the underlying database structure. Which is currently seen on the live site, we collect Scheduled monument under `National Heritage List for England list type` along with wether it's a listed building locally listed buildings are in a separate column. We then collect listed building grade under `Listing grade
`. Currently visualisation use one column to tell the server what colour the building should be painted. Two options here (that I can think of) are:
- Do something in the background (client side) that updates the `buildings.planning_list_cat` column in the db with two new values (locallyListed and scheduledMon). Then suppress these values from the drop down on the front end so users still only can pick from normal listing grades (I,II*,II) 
- Visualise more than one column at a time

@tomalrussell @mz8i One for todays discussion. 

@polly64 What this means for now is we can switch to visualising the Statutorily listed buildings simply enough and have the data in place for the others but mixing the different fields collected maybe more complex depending on what Tom and Maciek advise

**Comment by polly64** [comment]
Just to also raise -  listings/scheduled monuments are statutory data and can't be edited on our site. They need to go through the existing Historic England moderation process https://historicengland.org.uk/listing/the-list/minor-amendments/ which users need to be directed to in some way- (HE will basically will act as our first volunteer moderators for a subcategory   and will then double check whether there is an error. This is unlikely to happen often but we just need to make sure update/are notified of change.  This is one of the rare categories where we are providing statutory data so the procedure here for editing needs to be different.

**Comment by dominijk** [comment]
Moving discussion to [slack](https://colouringlondon.slack.com/archives/CM3PJTHQV/p1578658770028900)

**Comment by mz8i** [comment]
@polly64 can you please enter the final required colours for listed buildings in the table below. I copied over the colours from the initial design above as basis.

| label | colour | border
| --- | --- | ---
| Grade I | `#c72e08` |
| Grade II*  | `#e69800` |
| Grade II | `#9ebbc9` |
| Locally listed | `#ffbea1` |
| Scheduled monuments  | `#ffffff` | `#000000`
| Building in conservation area | `#aaaaaa` |

**Comment by polly64** [comment]
@mz8i Hi Maciek can we try loading these onto staging? and then if they're problems I can talk to tarn at weekend. I know I agreed with Dom to remove scheduled monuments but if they are still in database let's leave them in as u have them here.  Dom said I think there was some issue because the coloured polygons can relate to the whole site not just the building. I didn't look at any mapped and I can't remember  exactly what issue was.  We may need to ask him a quick question re this.  If there is any problem we can leave out for the  moment

**Comment by polly64** [comment]
@mz8i could u possibly load revised  colours as above on staging on thursday , and give listed buildings and local listed buildings in conservation areas the  pink border very slightly thinner than current black border many thanks

**Comment by polly64** [comment]
@mz8i @MeldaS   Hi Maciej can u look at Issue #160 .  I realise we don't seem to have got the 'Date of designation' for listed buildings or conservation areas up in the issue in the category?  This was Dom's v good idea a while back. Could u possibly add it?  It's v interesting for those interested in listed buildings even specialists. It's a unique feature we can easily add and  also important as it adds another data verification mechanism. I imagine it will be there for all listed buildings on the the complete excel sheet. thanks

**Comment by polly64** [comment]
@mz8i #574

adding separate planning issue as requested with all new filds inactive at present

Could u add a new separate section below the top 'planning portal link ' box
So it reads

'Planning Status'
'Designation and Protection' (not 'listing and protection')
Then just keep everything already under the 'Designation & Protection' section as it is
When u open up 'Planning Status' section could u make 4 new boxes:

'Is a planning application live for this site?' (make this inactive)
'Is demolition proposed?' (make inactive)
'Has this application recently been been approved/refused?' (make this inactive)
'Has the work been carried out? (make this inactive)
Then add a note below this
'For historical planning applications see Planning Portal link'
Ideally put hover over the first two inactive categories saying 'future proposed live link with Planning portal' but not essential
Move the rest of the demolition section to Dynamics
