### ISSUE TITLE
LOCATION

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#565]
- [ ] 1. Database column add `buildings.location_admin_authority`
- [ ] 1. Add db constraint using pk on table of borough names
- [ ] 2. Add bulk data (use UPRN lookup table) see separate issue 
- [ ] 3. Rename `Town` to `Borough` on front end populate from `location_admin_authority`
- [ ] 4. Disable edit to front end field - don't add to API whitelist as [docs](https://github.com/tomalrussell/colouring-london/blob/master/docs/adding-new-fields.md#in-api)
- [ ] 5. Add for extract  as [docs](https://github.com/tomalrussell/colouring-london/blob/master/docs/adding-new-fields.md#in-data-extracts)
- [ ] 6. Consider how this might enable the bulk download to be limited to a borough or wider feature of specific field
- [ ] 7. Consider if we want to create dumps of the data by borough (pros smaller files if user only wants part of data - cons doubles up storage on our server?)

**Comment by polly64** [comment]
1. @dominijk  is checking with open data community detailed impact of OS/ Geospatial commission UPRN etc release

2.  Update  subcats and prepopulate category accordingly 

3. Whats does this mean re adding OSM reference data?
