### ISSUE TITLE
One-time login flow

### ISSUE THREAD

**Issue by tomalrussell** [colouring-cities/colouring-core#62]
Alternative to reset password (or password login at all)

- [ ] Request login link (email address form)
- [ ] Generate token
- [ ] Send email
- [ ] Validate token and login
- [ ] Expire tokens

**Comment by dominijk** [comment]
Links to #290

**Comment by tomalrussell** [comment]
For reference (via https://github.com/tomalrussell/colouring-london/issues/61#issuecomment-522516290)
- https://www.lfgss.com/ have a nice example of email/temporary PIN login
- built with https://microco.sm/ forum software
  - API is open source https://github.com/microcosm-cc/microcosm/ (Go) as is the web client https://github.com/microcosm-cc/microweb (Python/Django)
  - with nice one-page API usage documentation http://microcosm-cc.github.io/
