### ISSUE TITLE
SURVIVAL MAPS &  HISTORICAL FOOTPRINT LAYERING & CONTENT GENERATION

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#632]
Create and layer cohort survival maps  starting with pre 1786 and 1787-1830to understand mortality and survival rates in stocks and resilient form. Begin to test layering of historical maps raster and vectorised to enable data and change to land use and form over last 150-200 years to be tracked, and better predicted. Also requires mechanisms for capturing strey data flor total floorspace loss/change

1. See attached image of  central London/holborn.  blue = 1830 street network plus surviving buildings built 1786-1830 and red represents pre1786 network and pre1786 survival buildings  How can this be integrated into existing system architecture?
2. Use Kiril Stanilov's vectorised historical networks plus dated building polygons from PH/Historic England) @tomalrussell @mz8i 
3. PH to work with Historic England on survival data - refined from NHLE
4. Link survival data nicely to designated asset section
5. Decide on how OS historical mapping data -raster image c1895 kindly offered by Chris Fleet at NLA  can also be tested in existing  system. 
5. PH to advance  work on vectorised historical  footprint computer vision  testing with Turing and with team designing methods of crowdsourced data nto these historical footprints
6. PH to work with flora Roumpani at Turing on dynamic procedura typologyl rules using these data 

[
![age_1786and1830](https://user-images.githubusercontent.com/42236514/96105591-1ef18d80-0ed2-11eb-8a89-fbc298f6505b.jpg)
](url)

**Comment by polly64** [comment]
Ist stage testing use Horwood 1792-99 map http://www.romanticlondon.org/horwoods-plan/#15/51.5078/-0.1484 with central London open map sheets from New York public library at https://digitalcollections.nypl.org/items/c6c5fde5-e71c-4bbc-e040-e00a18067bd1 showing all footprints. Find appropriate Faden 1819 revision. 1830? comparison with street blocks only?
![survivals closeup westminster_city](https://user-images.githubusercontent.com/42236514/103410386-e2ddd880-4b62-11eb-81c4-08b24951a520.jpg)
![Uploading Survival maps1786-1830  historic england overview.jpg…]()

**Comment by polly64** [comment]
Hi @mz8i  here's some stuff i'm doing in parallel on survival of age cohorts which  it would be  integrate into the dynamics section in some way https://github.com/colouring-london/colouring-london/issues/632. This is a longer term issue which will involve the SIG turing historical map group but prob worth thinking but at same time. . 

basically you'd have a survival map (in the dynamics section) and u could click on say 'survival from stock built 1837-1860'  (i.e. early victorian buildings) and it would provide centroids for the location of all buildings built during this period, footprints for survivals ( from which % survival could be calculalted) and georeferenced (and in the long term, vectorised historical maps/footprints) It would be really nice to test this for a single period e.g 1786-1830 for which Historic england have provided a point base map uploaded to the github site  and i have started work on disaggregating polygons

would be good to talk about this though we can leave to be done later

**Comment by polly64** [comment]
@mz8i and @tomalrussell ok thinking 1890's national library of scotland map (kindly offered by NLS) might be one to test and look at survival rates from 1890-2020 - might be able to get some help on this. here is the great side by side bing/historical map facility nls have - https://maps.nls.uk/geo/explore/side-by-side/#zoom=15&lat=51.41396&lon=-0.04357&layers=163&right=BingHyb - is this something we could integrate if they agree?

so steps (until we advance the computer vision work on vectorised footrpints)

a) accessing 1890 nls  Greater London map file held by turing 
b) adding georeferenced map
c) creating an on/ off button for the layer

or using nls  dual screen smehow as above

d) allowing historic buildings guys/volunteers to click on building polygons to mark whether they do or don;t  that appear to match the 1890 ones
e) enabling download of all matches as centroid data marked 'building survivals between 1890 and 2020

**Comment by tomalrussell** [comment]
See also [ONS basemaps demo](https://bothness.github.io/ons-basemaps/) which uses the NLS tiles for OS 1900s and 1937-61 maps - [config](https://github.com/bothness/ons-basemaps/blob/74ad774942f834043eedd15ca57159c6f969f5e8/js/config.js)

**Comment by polly64** [comment]
@tomalrussell @mz8i thanks tom - great thing about 1890s is it is so beautifully detailed, 

are u thinking that we could  have the comparison and nice slidy thing plus the ability to layer underneath and check?- how easy do u both think this is if we have access to high res maps which Chris at NLS has given us? 

In long run aim is to also have vectorised maps via Turing international Computer vision/Digital heritage SIG group which has grown significantly over last few months. we might be able to get technical support from members of this group interested in experimenting in this area
