### ISSUE TITLE
Bulk upload repository & 5 data upload methods

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#633]
Hi @tomalrussell and @mz8i do we have a bulk upload repository where gov depts/organisations can upload their datasets to us and they can be visible to other people while they are in a queue for us to check and then upload? 

 5 methods of generation

1. **In-house bulk upload of existing** data collation - allows for collation of existing data to address data fragmentation minimise unnecessary data reproduction to maximise   efficiency  (Local, borough and city-scale). Relevant mainly to planning

2. **In-house automated/semi-automated** data generation- allows for rapid generation of missing open datasets at city scale through inference; advances research into universal   attribute rules. (City-scale). Most relevant to 'Location', 'Use'. 'Age'(estimates only), 'Construction' 'Sustainability'

3. **Local Volunteered Geographic Information**  (VGI) - allows  generation of missing data not possible  to collect through automated/collation methods. (Building and street-scale). Includes verification of autogenerated  data (Building-scale to street scale). Historic environment input essential  'Team' and 'Dynamics' categories and for checking 'Age'/ age precision. Citizen input essential to all 'Community' categories and specific subcategories within planning and sustainability. School input relevant to checking 'Use' category, and building professionals to checking 'Construction'.

4. **Bulk VGI uploads** queued &  monitored in-house  esp.  from academic departments and local authorities  (Borough-scale to city-scale)

5. **Live streaming** proposed for planning data  (City-scale to be discussed with GLA and MHCLG further)

**Comment by dominijk** [comment]
I don't think we do, a good first step would be for them to list the data they can share (having checked they have rights to do so) and provide a link to it. This could happen on the forum?

**Comment by polly64** [comment]
good idea re the rights
