### ISSUE TITLE
Facilitate building attribute data upload for Type

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#725]
- [ ] Add copy tool
- [ ] Add verification button

## Consult list

- [ ] Activate [ ] Add ' Local typology/Architectural style' 
Add this initial dropdown to start with- CLHEAG will comment and suggest adjustments 

- Medieval/Tudor building
- Georgian terraced house
- Georgian building other
- Victorian high street building
- Victorian terraced house
- Victorian semi-detached house
- Victorian detached house
- Victorian board school
- Edwardian detached house
- Edwardian semi detached house
- Edwardian Mansion block 
- Interwar semi detached house
- Interwar detached house
- Interwar purpose built flats
- Interwar shopping parade
- Post war Low rise flats (1-5 storeys)
- Post war High rise flats
- Other

**Comment by matkoniecz** [comment]
@polly64

>  Add this initial dropdown to start with- CLHEAG will comment and suggest adjustments

I can do this, but doing it once would be much, much simpler than amending existing enumeration.
