### ISSUE TITLE
Facilitate building attribute data upload for Age

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#726]
@edwardchalstrey1 @matkoniecz CLHEAG priority

- [x] Move 'earliest' date box to above' latest' date box
- [ ] Add new extension box before 'facade date' with the question:
'Are there any significant later extensions? (Yes/No)
if 'yes' takes you to 'Date of extension/s?' (add date option and allow for all major extension dates to be added over time)
- [ ] Activate verification copy tool (as for all categories)
- [ ] Active improved copy tool (as for all categories)
- [x] Ask Maciek for file with my sources for age data for Camden
- [ ] add sources to 'Age 'category. 
Ask CLHEAG should you be able to add building date without a source?

**Comment by polly64** [comment]
@edwardchalstrey1 @matkoniecz 
- [ ] Ask Maciek for file with my sources for age data for Camden and add sources to 'Age 'category. 
- [ ] Move 'earliest' date box to above' latest' date box
- [ ] Add new extension box before 'facade date' with the question:
'Have there been any significant later extensions (Yes/No)
yes takes you to 'Date of extension/s?' (add date option and allow for multiple dates to be added
- [ ] make sure Source url link box is at bottom of everything and change question to 
'Please add any links to building age information here'
- [ ] - Ask CLHEAG should you be able to add data without a source? as discussion needed

**Comment by matkoniecz** [comment]
@polly64 

> Ask Maciek for file with my sources for age data for Camden

I did it already for one file and he submitted "Colouring London Polly's building age data file" email on 2022-01-22

Is it about yet another data file? Not sure should I ask him.

**Comment by matkoniecz** [comment]
> Add question marks to all sections

Which sections?

**Comment by polly64** [comment]
no this is right file

**Comment by polly64** [comment]
@matkoniecz can you email me file from Maciek now and i'll tell you which fields and where?

**Comment by polly64** [comment]
@matkoniecz it's fine leave question marks and i'll delete off actions

**Comment by matkoniecz** [comment]
> @matkoniecz can you email me file from Maciek now and i'll tell you which fields and where?

Done

**Comment by polly64** [comment]
@tomalrussell do you have my building age file from years ago called Tom4? It had all my age data in it but also the TOID links? wondered if you could possibly have a quick look for @matkoniecz

**Comment by edwardchalstrey1** [comment]
# Updated list 20/06/22

- [ ] Change name of first box to : 'Estimated start date' (this is the only one to be also linked to 'Teams''
- [ ] Add a Second box under it called 'Estimated completion date'
- [ ] Change existing the two  Earliest and latest possible date boxes to 
One saying Earliest and latest possible start dates and the other saying
Earliest and latest possible completion dates 
- [ ] then ' Has there been a major extension, etc see teams  above . Need separate source for this 
- [ ] Add 'Has Cladding been added later' below this. Only YES option . If yes then asks 'estimated date of cladding'
also with source
- [ ] Then have date of  'facade' last also with separate source link

Add a source link under 'facade'
Link up the major extension/retrofit etc section in team so it is reproduced here and whenever one is filled, it fills the other

    Add a 'Built from x to x ' option (see if you can copy from dynamics) below the first box
