### ISSUE TITLE
Facilitate building attribute data upload for Construction

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#727]
### Easy
- [ ] Add 'main secondary construction materials' list and allow them to tick however many are relevant. Use primary construction list (partial overlap with #568)
- [x] Change name from 'secondary construction materials to 'main secondary construction material/s'
- [x] Change sub category name from 'construction system' to 'construction system type'
- [ ] Add 'main construction system' list dropdown as follows:
- solid wall
- frame construction
- structural prefabricated panels 
- shell or membrane structures
- tensile structures 
- other (if other chosen provide free text box saying please specify
- [ ] Add 'source' box but allow multiple links to be added
-  [x] Swap the colour allocated for 'wood' for the colour allocated for 'other natural material' as a) the wood colour is too dark on black background, b) unsatisfying to colour in  (steel and RC colours very good/satisfying to use and brick ok, and  c) as so few wood buildings
Current colour key
name	rgb	hex
Timber (Light Brown) | #96613b
Stone (Cream) | #b5a859
Brick (Bright yellow) | #fca89d
Steel (Pink) | #5c8970
Glass (cream) | #ffffe3
Concrete (turquoise) | #beffe8
Other metal | #4d0000
Other natural material | #96613b
Other man-made material | `#c48a85'
- [ ] Add copy tool for each & a copy all option
- [ ] Add verification button for each

### Harder

- [ ] Download building age data, classify all pre 1900 buildings as main construction type = brick, and main construction system = solid wall, and upload. (several 100,000 might be worth asking Ed this)
- [ ] Add multiple visualisation options - for each of the 4 data types collected - as Maciek has done for Community category (can be done after feb)

### Other notes for PH

Explore collection of cladding and cladding date info 
Historical GiThub refs: 
https://github.com/colouring-cities/colouring-london/issues/605 #539

**Comment by matkoniecz** [comment]
@polly64 What needs to be changed here?

**Comment by polly64** [comment]
@matkoniecz just adding things now

**Comment by matkoniecz** [comment]
@polly64 

Are

> Secondary Construction Material/s
> Construction system

sections working currently in any way or were ever working? Not sure is it just placeholder or something got broken (I can check in repo history but if you remember it well it would be helpful)

**Comment by polly64** [comment]
@matkoniecz no secondary materials were never working we just had placeholder

**Comment by matkoniecz** [comment]
It is partially overlapping with #361

**Comment by matkoniecz** [comment]
@polly64 

> if other chosen provide free text box saying please specify

Is this freeform text box wanted? I remember plans to remove existing freeform text boxes.

**Comment by matkoniecz** [comment]
@polly64 

Do you want some form of ids for construction materials, like one displayed in land use? Currently empty text is a placeholder

![screen01](https://user-images.githubusercontent.com/899988/154481544-763976cd-8935-449c-988b-9a754543751f.png)


BTW, is it really useful to display identifiers in land use dropdown?

![screen](https://user-images.githubusercontent.com/899988/154481656-c573c7ff-9995-471c-ba98-395593b04cb7.png)

**Comment by matkoniecz** [comment]
It is OK to remove id.
