### ISSUE TITLE
Establish modes of communication for cross-country development

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#759]
- [ ] @tomalrussell to set up open calls
- [ ] @edwardchalstrey1 establish GH discussions as a platform for the community ( https://github.com/colouring-cities/colouring-london/discussions )

**Comment by matkoniecz** [comment]
> establish GH discussions as a platform for the community

Is it supposed to replace https://discuss.colouring.london/ ?
