### ISSUE TITLE
Has this ever been used for community activities in the past? - add from and to date options

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#773]
In Community view.

Extracted from  Facilitate building attribute data upload for Community #734

**Comment by matkoniecz** [comment]
@polly64

Opened a new issue for that as it is one of potentially more complex. It can be also done is the simplest possible form if that is a good fit.

>  For above item add from and to date options

How complex it should be? Is it OK to have "from year" and "to year"?

Or i it supposed to have "Latest possible start year"/"Earliest possible start date" like Age category?

I can imagine at least following:

- marking "till the current year when it sadly ended" vs "as of today it remains in use" (marking both as "to 2022" loses info, leaving open ended makes necessary to check history and makes very hard to mark in 2023 "still in use")
- open ended on one side
- multiple ranges ("from 1950 to 1960 and from 1985 to 2015")
- marking accuracy in dating ("from 2010-01-12" vs "from 2010" vs "from 2010s")

**Comment by polly64** [comment]
@matkoniecz yes year to year fine

could we have 2 options
a) always used for community activities - tick box OR
b) used community activities between 1920 and 1939

what do you think?

'

**Comment by matkoniecz** [comment]
Maybe "currently used for community activities - tick box"?

**Comment by polly64** [comment]
@matkoniecz 
Hi I think we need 3 questions here
1. Is the building used for any  type of community activities at the moment? ie daytime use as play centre
2. Has it always had community activities taking place within it? - i.e. was it built for these and is still used like a school
3. Was it and some point used for community activities and isn't now? ie was school now converted into housing
lets chat when we meet to get wording right
