### ISSUE TITLE
Extend Colouring London to include the whole of Britain

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#820]
Hopefully it should be possible to follow this guide: https://github.com/colouring-cities/colouring-london/tree/master/etl#readme and extend docs/scripts where needed

- Do we need a higher compute VM?
- Do we need more space?
- Are we renaming the site?
- Costs of VM?

**Comment by edwardchalstrey1** [comment]
Hi @polly64 ,

Just to let you know I have just had a chat with @matkoniecz  and he agrees that it makes sense for him to look at Colouring Britain, whilst I continue to work with you on the website feature priorities for CLHEAG.

In the meantime, it would be useful to know one thing: do we want to keep the website of colouringlondon.org or at some point do we rename it to colouringbritain.org ? Perhaps we could keep London and redirect to it from the Britain url, but change the branding/text on the website to say “Colouring Britain” once the update is enabled?

**Comment by polly64** [comment]
great thanks, yes he let me know just now.
yes completely agree let's wait for update and then change name

Polly Hudson
Senior Research Fellow, The Alan Turing Institute
Project Lead:  Colouring Cities Research Programme
https://www.turing.ac.uk/research/research-projects/colouring-london-and-colouring-cities-research-programme

The Alan Turing Institute is the UK's national institute for data science and artificial Intelligence.
The Alan Turing Institute is a limited liability company, registered in England with registered number 09512457 with registered offices at British Library, 96 Euston Road, London, England, NW1 2DB. We are also a charity registered in England with charity number 1162533. DISCLAIMER: Although we have taken reasonable precautions to ensure the completeness and accuracy of this e-mail, transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or be incomplete. If you receive a suspicious or unexpected email from us, or purporting to have been sent on our behalf, particularly containing different bank details, please do not reply to the email, click on any links, open any attachments, or comply with any instructions contained within it. Our Transparency Notice found here - https://www.turing.ac.uk/transparency-notice<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.turing.ac.uk%2Ftransparency-notice&data=04%7C01%7Cphudson%40turing.ac.uk%7C2324b5e120b4425faf7908d97c41c292%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637677444135244977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O4PMzDkukkzcBZkAX0ILaaWfe1T%2F7dsBTZsm%2FYKmolA%3D&reserved=0> sets out how and why we collect, store, use and share your personal data and it explains your rights and how to raise concerns with us.
________________________________
