### ISSUE TITLE
Draft some notes for the manual on "How to run/manage a Colouring Cities website"

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#899]
e.g. there should be some general guidance based on the Colouring London setup that other projects could roughly follow:

- Deploy the Node application on a cloud computing environment such as Azure, AWS, or on your own servers
- Manage Azure/Cloud Credits so that website stays live

The level of detail and hand-holding that this includes should probably be determined after chatting with PIs/engineers on other CC projects

**Comment by mdsimpson42** [comment]
- [ ] Add to the Technical Page

**Comment by matkoniecz** [comment]
Would it be added to https://github.com/colouring-cities/colouring-core/blob/master/docs/setup-dev-environment.md https://github.com/colouring-cities/colouring-core/blob/master/docs/setup-production-environment.md or somewhere else?

**Comment by polly64** [comment]
@matkoniecz would be good to be on all appropriate areas of GitHub but also to have a summary for PIs to understand on technical page of manual as they will have to plan and coordinate funding for this
