### ISSUE TITLE
Planning -> What is its grade?: add option "Other"

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-core#927]
see https://github.com/colouring-cities/colouring-london/issues/926#issuecomment-1252452994

**Comment by matkoniecz** [comment]
@polly64 

How it should appear in Designation/protection legend? 

As "Other Listed"? "Grade ? Listed"

**Comment by matkoniecz** [comment]
@polly64 ping

**Comment by polly64** [comment]
@matkoniecz 'Other grade'
